from __future__ import annotations

"""
Compare candidate coordinate spaces for Bayesian optimization of Cu-binding peptides.

Candidate spaces
----------------
1) encoder_mu
   Raw 64-D GRU-VAE encoder mean.

2) encoder_h0
   Training-standardized GRU-VAE encoder mean:
       h0 = (mu - latent_mean) / latent_std

3) diffusion_epsilon
   64-D DDIM-inverted diffusion base-noise coordinates.

4) decoder_mu_back [optional; requires .pt checkpoint]
   Actual 64-D latent passed into the GRU decoder after:
       epsilon -> DDIM sample -> h_back -> unstandardize -> mu_back
   This is a valid generative latent representation, although it is downstream
   of the diffusion map.

5) decoder_initial_hidden [diagnostic only; requires .pt checkpoint]
   128-D initial hidden state generated by z_to_h(mu_back).
   This is NOT recommended as a direct BO search space because an arbitrary
   128-D hidden vector does not have a defined inverse to the decoder latent z.

Important:
The true decoder recurrent input at each position is
    concat(token_embedding(previous_token), z)
and therefore depends on the decoded token trajectory. It is not an independent
continuous generative coordinate. This script deliberately does NOT rank that
teacher-forced/recurrent input tensor as a valid BO space.

The script evaluates each space using four complementary criteria:

A. Geometry / intrinsic dimensionality
B. Local objective smoothness
C. Gaussian-process held-out learnability
D. Offline multi-objective Bayesian optimization with ParEGO on the fixed
   evaluated candidate pool

The offline BO benchmark is a fair *representation comparison*, not a substitute
for a prospective black-box BO experiment.

Objectives are assumed to be maximized:
    chelation_sub
    solubility_sub
    stability_sub
    expression_sub
"""

import argparse
import importlib.util
import json
import math
import os
import random
import re
import sys
import warnings
from pathlib import Path
from typing import Dict, List, Sequence, Tuple, Optional

import numpy as np
import pandas as pd
import torch
from scipy.stats import norm, spearmanr
from sklearn.decomposition import PCA
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import ConstantKernel, Matern, WhiteKernel
from sklearn.exceptions import ConvergenceWarning
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt


DEFAULT_OBJECTIVES = [
    "chelation_sub",
    "solubility_sub",
    "stability_sub",
    "expression_sub",
]


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def sorted_prefixed_columns(df: pd.DataFrame, prefix: str) -> List[str]:
    """
    Return only coordinate columns with an integer suffix.

    Examples:
      prefix="epsilon_" -> epsilon_00 ... epsilon_63

    This deliberately excludes metadata columns such as:
      epsilon_norm

    The earlier implementation used startswith(prefix), which incorrectly
    included epsilon_norm and made diffusion_epsilon 65-D instead of 64-D.
    """
    pattern = re.compile(r"^" + re.escape(prefix) + r"(\d+)$")
    matched = []
    for c in df.columns:
        m = pattern.match(c)
        if m:
            matched.append((int(m.group(1)), c))
    matched.sort(key=lambda x: x[0])
    return [c for _, c in matched]


def finite_rows(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    return np.isfinite(X).all(axis=1) & np.isfinite(Y).all(axis=1)


def import_module_py314_safe(path: str, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(module_name, None)
        raise
    return module


def pareto_mask_max(Y: np.ndarray) -> np.ndarray:
    """Return nondominated mask for maximization."""
    Y = np.asarray(Y, dtype=float)
    n = len(Y)
    keep = np.ones(n, dtype=bool)
    for i in range(n):
        if not keep[i]:
            continue
        # j dominates i if all Yj >= Yi and at least one >.
        dominates_i = np.all(Y >= Y[i], axis=1) & np.any(Y > Y[i], axis=1)
        dominates_i[i] = False
        if np.any(dominates_i):
            keep[i] = False
    return keep


def normalize_objectives_global(Y: np.ndarray):
    lo = np.nanmin(Y, axis=0)
    hi = np.nanmax(Y, axis=0)
    span = np.maximum(hi - lo, 1e-12)
    Yn = (Y - lo) / span
    return Yn, lo, hi


# ---------------------------------------------------------------------
# Load representations
# ---------------------------------------------------------------------

def load_direct_spaces(df: pd.DataFrame) -> Dict[str, np.ndarray]:
    spaces = {}

    mu_cols = sorted_prefixed_columns(df, "mu_")
    h_cols = sorted_prefixed_columns(df, "h0_standardized_")
    eps_cols = sorted_prefixed_columns(df, "epsilon_")

    print(
        "Detected coordinate columns: "
        f"mu={len(mu_cols)}, h0={len(h_cols)}, epsilon={len(eps_cols)}"
    )

    if mu_cols:
        spaces["encoder_mu"] = df[mu_cols].to_numpy(dtype=np.float64)

    if h_cols:
        spaces["encoder_h0"] = df[h_cols].to_numpy(dtype=np.float64)

    if eps_cols:
        spaces["diffusion_epsilon"] = df[eps_cols].to_numpy(dtype=np.float64)

    return spaces


@torch.no_grad()
def derive_decoder_spaces(
    df: pd.DataFrame,
    checkpoint_path: str,
    finetune_script: str,
    device: torch.device,
    batch_size: int,
) -> Dict[str, np.ndarray]:
    """
    Derive actual decoder-side latent coordinates using the selected diffusion checkpoint.

    Requires the real .pt file, not only the .json sidecar.
    """
    module = import_module_py314_safe(
        finetune_script,
        "cu_gruvae_diffusion_module_for_space_comparison",
    )
    ckpt = torch.load(checkpoint_path, map_location=device)

    cfg_dict = ckpt["model_config"]
    diff_dict = ckpt["diffusion_config"]

    cfg = module.ModelConfig(**cfg_dict)
    diff_cfg = module.DiffusionConfig(**diff_dict)

    vae = module.GRUVAE(cfg).to(device)
    diffusion = module.LatentDiffusion(cfg.latent_dim, diff_cfg).to(device)

    vae.load_state_dict(ckpt["vae_state_dict"], strict=True)
    diffusion.load_state_dict(ckpt["diffusion_state_dict"], strict=True)
    vae.eval()
    diffusion.eval()

    latent_mean = ckpt["latent_mean"].to(device).float()
    latent_std = ckpt["latent_std"].to(device).float().clamp_min(1e-6)

    eps_cols = sorted_prefixed_columns(df, "epsilon_")
    if not eps_cols:
        raise ValueError("Coordinate CSV has no epsilon_* columns.")

    eps_all = torch.tensor(
        df[eps_cols].to_numpy(dtype=np.float32),
        device=device,
    )

    ddim_steps = int(ckpt.get("args", {}).get("ddim_steps", 20))

    mu_back_all = []
    hidden_all = []

    for start in range(0, len(df), batch_size):
        eps = eps_all[start:start + batch_size]
        h_back = diffusion.ddim_sample(eps, inference_steps=ddim_steps)
        mu_back = (
            h_back * latent_std.unsqueeze(0)
            + latent_mean.unsqueeze(0)
        )
        initial_hidden = vae.dec.z_to_h(mu_back)

        mu_back_all.append(mu_back.detach().cpu().numpy())
        hidden_all.append(initial_hidden.detach().cpu().numpy())

    return {
        "decoder_mu_back": np.concatenate(mu_back_all, axis=0).astype(np.float64),
        # Diagnostic-only representation.
        "decoder_initial_hidden": np.concatenate(hidden_all, axis=0).astype(np.float64),
    }


# ---------------------------------------------------------------------
# Geometry / intrinsic dimensionality
# ---------------------------------------------------------------------

def geometry_metrics(X: np.ndarray) -> Dict[str, float]:
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    pca = PCA()
    pca.fit(Xs)
    eig = pca.explained_variance_
    ratio = pca.explained_variance_ratio_

    participation = float((eig.sum() ** 2) / np.maximum((eig ** 2).sum(), 1e-12))
    cumulative = np.cumsum(ratio)

    def n_for(v):
        return int(np.searchsorted(cumulative, v) + 1)

    return {
        "dimension": int(X.shape[1]),
        "effective_dimension_participation_ratio": participation,
        "pca_components_90pct": n_for(0.90),
        "pca_components_95pct": n_for(0.95),
        "pca_components_99pct": n_for(0.99),
        "pc1_explained_fraction": float(ratio[0]),
        "pc2_cumulative_fraction": float(cumulative[min(1, len(cumulative)-1)]),
        "mean_feature_std_raw": float(np.mean(np.std(X, axis=0))),
    }


# ---------------------------------------------------------------------
# Local objective smoothness
# ---------------------------------------------------------------------

def local_objective_metrics(
    X: np.ndarray,
    Y: np.ndarray,
    k: int,
    pair_sample: int,
    seed: int,
) -> Dict[str, float]:
    """
    A BO-friendly representation should tend to put similar objective vectors nearby.

    Reports:
      - kNN objective L2
      - correlation of representation distance with objective distance
    """
    Xs = StandardScaler().fit_transform(X)
    Yn, _, _ = normalize_objectives_global(Y)

    k_eff = min(k + 1, len(Xs))
    nn = NearestNeighbors(n_neighbors=k_eff, metric="euclidean")
    nn.fit(Xs)
    dists, inds = nn.kneighbors(Xs)

    # Drop self-neighbor.
    dists = dists[:, 1:]
    inds = inds[:, 1:]

    obj_d = []
    for i in range(len(Xs)):
        dif = Yn[inds[i]] - Yn[i]
        obj_d.extend(np.linalg.norm(dif, axis=1).tolist())

    rng = np.random.default_rng(seed)
    m = min(pair_sample, len(Xs) * 20)
    a = rng.integers(0, len(Xs), size=m)
    b = rng.integers(0, len(Xs), size=m)
    ok = a != b
    a, b = a[ok], b[ok]

    dx = np.linalg.norm(Xs[a] - Xs[b], axis=1)
    dy = np.linalg.norm(Yn[a] - Yn[b], axis=1)

    rho = spearmanr(dx, dy, nan_policy="omit").statistic
    pearson = np.corrcoef(dx, dy)[0, 1] if len(dx) > 2 else np.nan

    return {
        "knn_k": int(k_eff - 1),
        "knn_objective_l2_mean": float(np.mean(obj_d)),
        "knn_objective_l2_median": float(np.median(obj_d)),
        "pair_distance_objective_spearman": float(rho),
        "pair_distance_objective_pearson": float(pearson),
    }


# ---------------------------------------------------------------------
# Gaussian-process held-out learnability
# ---------------------------------------------------------------------

def build_gp(random_state: int):
    # Isotropic Matern after feature standardization:
    # fair across coordinate systems and much more stable than 64+ ARD parameters.
    kernel = (
        ConstantKernel(1.0, (1e-2, 1e2))
        * Matern(length_scale=1.0, length_scale_bounds=(1e-2, 1e2), nu=2.5)
        + WhiteKernel(noise_level=1e-3, noise_level_bounds=(1e-7, 1e0))
    )
    return GaussianProcessRegressor(
        kernel=kernel,
        alpha=1e-8,
        normalize_y=True,
        n_restarts_optimizer=0,
        random_state=random_state,
    )


def gp_learnability(
    X: np.ndarray,
    Y: np.ndarray,
    objective_names: Sequence[str],
    train_sizes: Sequence[int],
    test_fraction: float,
    seeds: Sequence[int],
) -> pd.DataFrame:
    rows = []
    n = len(X)

    for seed in seeds:
        rng = np.random.default_rng(seed)
        perm = rng.permutation(n)
        n_test = max(1, int(round(test_fraction * n)))
        test_idx = perm[:n_test]
        pool_idx = perm[n_test:]

        for train_size in train_sizes:
            train_size = min(int(train_size), len(pool_idx))
            train_idx = pool_idx[:train_size]

            scaler = StandardScaler().fit(X[train_idx])
            Xtr = scaler.transform(X[train_idx])
            Xte = scaler.transform(X[test_idx])

            per_obj = []
            for j, obj in enumerate(objective_names):
                gp = build_gp(seed + j)
                gp.fit(Xtr, Y[train_idx, j])
                pred, std = gp.predict(Xte, return_std=True)
                std = np.maximum(std, 1e-9)

                rmse = math.sqrt(mean_squared_error(Y[test_idx, j], pred))
                mae = mean_absolute_error(Y[test_idx, j], pred)
                r2 = r2_score(Y[test_idx, j], pred)
                spear = spearmanr(Y[test_idx, j], pred, nan_policy="omit").statistic

                # Gaussian negative log predictive density.
                resid = Y[test_idx, j] - pred
                nlpd = np.mean(
                    0.5 * np.log(2.0 * np.pi * std**2)
                    + 0.5 * (resid / std)**2
                )

                coverage95 = np.mean(np.abs(resid) <= 1.96 * std)

                per_obj.append((rmse, mae, r2, spear, nlpd, coverage95))

                rows.append({
                    "seed": seed,
                    "train_size": train_size,
                    "objective": obj,
                    "rmse": rmse,
                    "mae": mae,
                    "r2": r2,
                    "spearman": spear,
                    "nlpd": nlpd,
                    "coverage95": coverage95,
                })

            arr = np.asarray(per_obj, dtype=float)
            rows.append({
                "seed": seed,
                "train_size": train_size,
                "objective": "__MEAN__",
                "rmse": float(np.nanmean(arr[:, 0])),
                "mae": float(np.nanmean(arr[:, 1])),
                "r2": float(np.nanmean(arr[:, 2])),
                "spearman": float(np.nanmean(arr[:, 3])),
                "nlpd": float(np.nanmean(arr[:, 4])),
                "coverage95": float(np.nanmean(arr[:, 5])),
            })

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------
# Offline multi-objective BO benchmark: ParEGO
# ---------------------------------------------------------------------

def augmented_tchebycheff(Yn: np.ndarray, w: np.ndarray, rho: float = 0.05):
    """
    Maximization scalarization toward ideal point 1.
    Larger is better.
    """
    d = 1.0 - Yn
    loss = np.max(w[None, :] * d, axis=1) + rho * np.sum(w[None, :] * d, axis=1)
    return -loss


def expected_improvement_max(mu, sigma, best):
    sigma = np.maximum(sigma, 1e-12)
    z = (mu - best) / sigma
    return (mu - best) * norm.cdf(z) + sigma * norm.pdf(z)


def monte_carlo_hypervolume_max(
    Y: np.ndarray,
    ref: np.ndarray,
    upper: np.ndarray,
    samples_unit: np.ndarray,
):
    """
    Fixed-sample Monte Carlo hypervolume for maximization.
    Same MC samples are reused for all spaces/runs, making comparisons fair.
    """
    if len(Y) == 0:
        return 0.0

    P = Y[pareto_mask_max(Y)]
    box = np.maximum(upper - ref, 1e-12)
    samples = ref[None, :] + samples_unit * box[None, :]

    dominated = np.zeros(len(samples), dtype=bool)
    # chunk Pareto points to keep memory bounded
    for p in P:
        dominated |= np.all(samples <= p[None, :], axis=1)

    return float(np.prod(box) * dominated.mean())


def parego_offline_bo(
    X: np.ndarray,
    Y: np.ndarray,
    init_size: int,
    budget: int,
    seeds: Sequence[int],
    hv_mc_samples: int,
) -> pd.DataFrame:
    """
    Discrete-candidate offline ParEGO benchmark.

    At each iteration:
      1. random objective scalarization
      2. fit a GP on observed scalarized values
      3. calculate EI over all remaining evaluated candidates
      4. reveal the objective vector of the selected candidate
      5. record hypervolume

    This tests whether a coordinate space makes BO sample-efficient on a common
    finite candidate pool.
    """
    Yn, _, _ = normalize_objectives_global(Y)
    ref = np.full(Y.shape[1], -0.05, dtype=float)
    upper = np.full(Y.shape[1], 1.05, dtype=float)

    # Common fixed MC integration points.
    common_rng = np.random.default_rng(99173)
    hv_samples = common_rng.random((hv_mc_samples, Y.shape[1]))

    rows = []
    n = len(X)
    budget = min(int(budget), n)

    for seed in seeds:
        rng = np.random.default_rng(seed)
        init = rng.choice(n, size=min(init_size, budget), replace=False).tolist()
        observed = list(init)
        remaining = set(range(n)) - set(observed)

        # Fit input scaling from full candidate geometry only.
        # This does not use objectives, so it does not leak target information.
        Xs = StandardScaler().fit_transform(X)

        for step in range(len(observed), budget + 1):
            hv = monte_carlo_hypervolume_max(
                Yn[observed], ref, upper, hv_samples
            )
            rows.append({
                "seed": seed,
                "n_evaluated": len(observed),
                "hypervolume": hv,
            })

            if len(observed) >= budget or not remaining:
                break

            w = rng.dirichlet(np.ones(Y.shape[1]))
            scalar = augmented_tchebycheff(Yn[observed], w)

            gp = build_gp(seed + step)
            gp.fit(Xs[observed], scalar)

            rem = np.fromiter(remaining, dtype=int)
            mu, std = gp.predict(Xs[rem], return_std=True)
            best_scalar = float(np.max(scalar))
            ei = expected_improvement_max(mu, std, best_scalar)

            next_idx = int(rem[int(np.argmax(ei))])
            observed.append(next_idx)
            remaining.remove(next_idx)

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------
# Aggregate ranking
# ---------------------------------------------------------------------

def aggregate_gp(gp_df: pd.DataFrame, max_train_size: int):
    d = gp_df[
        (gp_df["objective"] == "__MEAN__")
        & (gp_df["train_size"] == max_train_size)
    ]
    return {
        "gp_rmse": float(d["rmse"].mean()),
        "gp_r2": float(d["r2"].mean()),
        "gp_spearman": float(d["spearman"].mean()),
        "gp_nlpd": float(d["nlpd"].mean()),
        "gp_coverage95": float(d["coverage95"].mean()),
    }


def rank_spaces(summary: pd.DataFrame) -> pd.DataFrame:
    """
    Lower score is better.
    Rank only spaces flagged bo_eligible=True.
    """
    d = summary.copy()
    eligible = d["bo_eligible"].astype(bool)

    metrics = [
        ("gp_rmse", True),
        ("gp_r2", False),
        ("gp_spearman", False),
        ("knn_objective_l2_mean", True),
        ("pair_distance_objective_spearman", False),
        ("final_hypervolume", False),
    ]

    rank_cols = []
    for metric, lower_better in metrics:
        if metric not in d.columns:
            continue
        col = f"rank_{metric}"
        d[col] = np.nan
        d.loc[eligible, col] = d.loc[eligible, metric].rank(
            ascending=lower_better,
            method="average",
        )
        rank_cols.append(col)

    d["mean_rank"] = d[rank_cols].mean(axis=1, skipna=True)
    d.loc[~eligible, "mean_rank"] = np.nan
    d["recommended_order"] = d["mean_rank"].rank(method="min")
    d.loc[~eligible, "recommended_order"] = np.nan
    return d.sort_values(["recommended_order", "space"], na_position="last")


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------

def save_gp_plot(all_gp: pd.DataFrame, out_dir: Path):
    means = (
        all_gp[all_gp["objective"] == "__MEAN__"]
        .groupby(["space", "train_size"], as_index=False)["rmse"]
        .mean()
    )
    fig, ax = plt.subplots(figsize=(9, 6))
    for space, g in means.groupby("space"):
        ax.plot(g["train_size"], g["rmse"], marker="o", label=space)
    ax.set_xlabel("GP training size")
    ax.set_ylabel("Mean held-out objective RMSE")
    ax.set_title("GP learnability by candidate BO space")
    ax.grid(True, alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_dir / "gp_rmse_vs_training_size.png", dpi=300)
    plt.close(fig)


def save_bo_plot(all_bo: pd.DataFrame, out_dir: Path):
    means = (
        all_bo.groupby(["space", "n_evaluated"], as_index=False)["hypervolume"]
        .mean()
    )
    fig, ax = plt.subplots(figsize=(9, 6))
    for space, g in means.groupby("space"):
        ax.plot(g["n_evaluated"], g["hypervolume"], label=space)
    ax.set_xlabel("Number of objective evaluations")
    ax.set_ylabel("Monte Carlo hypervolume")
    ax.set_title("Offline ParEGO sample efficiency by candidate space")
    ax.grid(True, alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_dir / "offline_parego_hypervolume.png", dpi=300)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser(
        description="Compare GRU-VAE and diffusion coordinate spaces for peptide BO."
    )
    p.add_argument("--coordinate-csv", required=True)
    p.add_argument(
        "--objective-cols",
        nargs="+",
        default=DEFAULT_OBJECTIVES,
    )
    p.add_argument("--out-dir", default="bo_space_comparison")

    # Optional derivation of decoder-side spaces.
    p.add_argument(
        "--checkpoint",
        default="",
        help="Optional real .pt best-inversion checkpoint, not the .json sidecar.",
    )
    p.add_argument(
        "--finetune-script",
        default="",
        help="Fine-tuning .py defining GRUVAE and LatentDiffusion.",
    )
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--batch-size", type=int, default=256)

    # Geometry/locality.
    p.add_argument("--knn-k", type=int, default=5)
    p.add_argument("--pair-sample", type=int, default=30000)

    # GP held-out validation.
    p.add_argument(
        "--gp-train-sizes",
        type=int,
        nargs="+",
        default=[64, 128, 256, 512, 1024],
    )
    p.add_argument("--gp-test-fraction", type=float, default=0.20)
    p.add_argument(
        "--gp-seeds",
        type=int,
        nargs="+",
        default=[11, 22, 33],
    )

    # Offline ParEGO benchmark.
    p.add_argument("--skip-offline-bo", action="store_true")
    p.add_argument("--bo-init-size", type=int, default=32)
    p.add_argument("--bo-budget", type=int, default=100)
    p.add_argument(
        "--bo-seeds",
        type=int,
        nargs="+",
        default=[101, 202, 303],
    )
    p.add_argument("--hv-mc-samples", type=int, default=30000)

    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    set_seed(args.seed)

    # The GP optimizer often drives the learned observation-noise term to the
    # lower bound for these nearly deterministic objective labels. That is not
    # a failure; suppress the repetitive sklearn warning so the comparison log
    # remains readable.
    warnings.filterwarnings(
        "ignore",
        category=ConvergenceWarning,
        message=r".*noise_level.*lower bound.*",
    )

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(args.coordinate_csv)
    missing_obj = [c for c in args.objective_cols if c not in df.columns]
    if missing_obj:
        raise ValueError(f"Missing objective columns: {missing_obj}")

    Y = df[args.objective_cols].to_numpy(dtype=np.float64)
    spaces = load_direct_spaces(df)

    if args.checkpoint or args.finetune_script:
        if not (args.checkpoint and args.finetune_script):
            raise ValueError(
                "To derive decoder-side spaces, supply BOTH --checkpoint and --finetune-script."
            )
        spaces.update(
            derive_decoder_spaces(
                df=df,
                checkpoint_path=args.checkpoint,
                finetune_script=args.finetune_script,
                device=torch.device(args.device),
                batch_size=args.batch_size,
            )
        )

    if not spaces:
        raise ValueError("No candidate spaces could be loaded.")

    # Sanity checks: the three core latent coordinate systems are all expected
    # to have exactly latent_dim=64 for the current H64/Z64 model.
    expected_dim = 64
    for core_name in ["encoder_mu", "encoder_h0", "diffusion_epsilon"]:
        if core_name in spaces and spaces[core_name].shape[1] != expected_dim:
            raise ValueError(
                f"{core_name} has {spaces[core_name].shape[1]} columns, "
                f"but expected {expected_dim}. Check coordinate-column parsing."
            )

    # Same finite rows across all spaces for a fair comparison.
    common = np.isfinite(Y).all(axis=1)
    for X in spaces.values():
        common &= np.isfinite(X).all(axis=1)

    Y = Y[common]
    df = df.loc[common].reset_index(drop=True)
    spaces = {k: v[common] for k, v in spaces.items()}

    print(f"Rows used in fair comparison: {len(Y)}")
    print(f"Spaces: {[(k, v.shape) for k, v in spaces.items()]}")

    all_gp = []
    all_bo = []
    summaries = []

    # decoder_initial_hidden is a derived diagnostic representation, not a
    # directly invertible optimization coordinate.
    ineligible = {"decoder_initial_hidden"}

    for space_name, X in spaces.items():
        print(f"\n=== {space_name} shape={X.shape} ===")

        geom = geometry_metrics(X)
        local = local_objective_metrics(
            X, Y,
            k=args.knn_k,
            pair_sample=args.pair_sample,
            seed=args.seed,
        )

        gp = gp_learnability(
            X=X,
            Y=Y,
            objective_names=args.objective_cols,
            train_sizes=args.gp_train_sizes,
            test_fraction=args.gp_test_fraction,
            seeds=args.gp_seeds,
        )
        gp.insert(0, "space", space_name)
        all_gp.append(gp)

        max_gp_size = int(gp["train_size"].max())
        gp_summary = aggregate_gp(gp, max_gp_size)

        bo_eligible = space_name not in ineligible

        final_hv = np.nan
        hv_auc = np.nan
        if not args.skip_offline_bo and bo_eligible:
            bo = parego_offline_bo(
                X=X,
                Y=Y,
                init_size=args.bo_init_size,
                budget=args.bo_budget,
                seeds=args.bo_seeds,
                hv_mc_samples=args.hv_mc_samples,
            )
            bo.insert(0, "space", space_name)
            all_bo.append(bo)

            final_rows = bo[bo["n_evaluated"] == bo["n_evaluated"].max()]
            final_hv = float(final_rows["hypervolume"].mean())

            # Mean hypervolume AUC across seeds.
            aucs = []
            for seed, g in bo.groupby("seed"):
                g = g.sort_values("n_evaluated")
                aucs.append(np.trapezoid(g["hypervolume"], g["n_evaluated"]))
            hv_auc = float(np.mean(aucs))

        summaries.append({
            "space": space_name,
            "bo_eligible": bo_eligible,
            **geom,
            **local,
            **gp_summary,
            "final_hypervolume": final_hv,
            "hypervolume_auc": hv_auc,
        })

    gp_all = pd.concat(all_gp, ignore_index=True)
    gp_all.to_csv(out_dir / "gp_learnability_all_spaces.csv", index=False)

    if all_bo:
        bo_all = pd.concat(all_bo, ignore_index=True)
        bo_all.to_csv(out_dir / "offline_parego_all_spaces.csv", index=False)
        save_bo_plot(bo_all, out_dir)

    summary = pd.DataFrame(summaries)
    ranked = rank_spaces(summary)
    ranked.to_csv(out_dir / "bo_space_comparison_summary_ranked.csv", index=False)

    save_gp_plot(gp_all, out_dir)

    # Human-readable recommendation.
    eligible_ranked = ranked[ranked["bo_eligible"]].sort_values("mean_rank")
    best = eligible_ranked.iloc[0]

    lines = []
    lines.append("BAYESIAN-OPTIMIZATION CANDIDATE-SPACE COMPARISON")
    lines.append("=" * 88)
    lines.append(f"n_rows={len(Y)}")
    lines.append(f"objectives={args.objective_cols}")
    lines.append("")
    lines.append("RANKED SUMMARY")
    lines.append("-" * 88)

    show_cols = [
        "space",
        "dimension",
        "effective_dimension_participation_ratio",
        "pca_components_95pct",
        "knn_objective_l2_mean",
        "pair_distance_objective_spearman",
        "gp_rmse",
        "gp_r2",
        "gp_spearman",
        "final_hypervolume",
        "hypervolume_auc",
        "mean_rank",
    ]
    lines.append(ranked[show_cols].to_string(index=False))
    lines.append("")
    lines.append(f"TOP ELIGIBLE SPACE BY COMPOSITE RANK: {best['space']}")
    lines.append("")
    lines.append("INTERPRETATION RULES")
    lines.append("-" * 88)
    lines.append("Lower GP RMSE and kNN objective distance are better.")
    lines.append("Higher GP R2, GP Spearman, distance/objective Spearman, hypervolume, and HV-AUC are better.")
    lines.append(
        "encoder_mu and encoder_h0 are related by an affine standardization, so a well-scaled GP may perform similarly."
    )
    lines.append(
        "diffusion_epsilon is preferable only if it improves objective learnability and/or offline BO sample efficiency enough to justify DDIM inversion/sampling error."
    )
    lines.append(
        "decoder_initial_hidden is diagnostic only and is excluded from BO ranking because arbitrary hidden vectors do not map uniquely back to decoder latents."
    )
    lines.append(
        "The recurrent decoder input concat(token_embedding, z) is trajectory-dependent and should not be optimized directly."
    )
    lines.append(
        "Final confirmation should use prospective BO with the same initial design, qEHVI/ParEGO settings, objective-evaluation budget, and random seeds."
    )

    report = "\n".join(lines) + "\n"
    (out_dir / "bo_space_comparison_report.txt").write_text(report, encoding="utf-8")
    print(report)
    print(f"Saved results to: {out_dir.resolve()}")


if __name__ == "__main__":
    main()
