from __future__ import annotations

"""
GP surrogate validation benchmark for peptide BO latent representations.

Primary comparison
------------------
1) diffusion_epsilon
   DDIM base-noise coordinates used by epsilon-space BO.

2) vae_h0_ddim
   Standardized VAE latent h produced by deterministic DDIM sampling from each
   epsilon point. This is the continuous latent passed (after unstandardizing)
   to the frozen VAE decoder, so it gives the fairest same-point comparison
   against epsilon for the already black-box-scored epsilon samples.

3) vae_h0_encoded
   Standardized encoder-mu of the decoded peptide itself. This tests the direct
   VAE encoder representation of the same evaluated peptide.

4) realnvp (optional)
   Post-flow coordinates loaded from a separate CSV and matched by peptide.
   Auto-detects common prefixes such as zK_, zk_, flow_, postflow_, etc.

Inputs
------
- The SAME latent-diffusion checkpoint used by the epsilon smoothness test.
- Original Cu black-box-scored CSV used for source-center selection.
- Corrected epsilon neighbor details CSV containing the true four black-box
  objective values for every decoded neighbor peptide.
- Optional corrected decoded-center CSV. Centers are included when their
  objective columns are available.
- Optional RealNVP coordinate CSV.

The script reconstructs the exact epsilon samples generated by
diagnose_epsilon_objective_smoothness_corrected.py using the same center
selection, seed, sigmas, neighbor count, sphere projection and DDIM steps.

Metrics per objective
---------------------
- RMSE
- MAE
- R^2
- Spearman correlation
- Gaussian negative log predictive density (NLPD)
- uncertainty calibration:
    * empirical 50/80/90/95% predictive interval coverage
    * calibration ECE = mean |coverage - nominal|
    * 95% coverage error
    * standardized residual mean/std
- performance versus training-set size

Evaluation design
-----------------
- SAME train/test groups for every representation.
- Default split is by decoded PEPTIDE, not by row, preventing identical peptide
  leakage when a decoder maps multiple latent points to the same sequence.
- Nested training subsets are reused across representations for fairness.
- Independent exact SingleTaskGP models are fitted per objective.
- Inputs are standardized using TRAINING data only.
- Targets are standardized internally by BoTorch's Standardize outcome transform.

Notes
-----
Exact GPs scale cubically with training size. Start with:
    --train-sizes 64 128 256 512 1024
and increase only if runtime/memory are acceptable.

For a publication-quality representation comparison, use several split seeds,
e.g.:
    --split-seeds 11 22 33 44 55
"""

import argparse
import json
import math
import os
import random
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

import gpytorch
from gpytorch.kernels import MaternKernel, RBFKernel, ScaleKernel
from gpytorch.mlls import ExactMarginalLogLikelihood

from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from botorch.models.transforms.outcome import Standardize

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


AA = "ACDEFGHIKLMNPQRSTVWY"
AA_TO_I = {a: i for i, a in enumerate(AA)}
I_TO_AA = {i: a for i, a in enumerate(AA)}
SEQ_LEN = 10
VOCAB = 20

DEFAULT_OBJECTIVES = [
    "chelation_sub",
    "solubility_sub",
    "stability_sub",
    "expression_sub",
]


# ============================================================================
# Reproducibility / utilities
# ============================================================================

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def clean_peptide(x: object) -> Optional[str]:
    s = str(x).strip().upper()
    if len(s) != SEQ_LEN:
        return None
    if any(ch not in AA_TO_I for ch in s):
        return None
    return s


def onehot_encode_peptides(peptides: Sequence[str]) -> torch.Tensor:
    x = torch.zeros((len(peptides), SEQ_LEN, VOCAB), dtype=torch.float32)
    for n, pep in enumerate(peptides):
        p = clean_peptide(pep)
        if p is None:
            raise ValueError(f"Invalid peptide: {pep!r}")
        for t, aa in enumerate(p):
            x[n, t, AA_TO_I[aa]] = 1.0
    return x


def rankdata_average(x: np.ndarray) -> np.ndarray:
    return pd.Series(np.asarray(x, dtype=float)).rank(method="average").to_numpy(float)


def spearman_safe(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    mask = np.isfinite(a) & np.isfinite(b)
    a = a[mask]
    b = b[mask]
    if len(a) < 3:
        return float("nan")
    ra = rankdata_average(a)
    rb = rankdata_average(b)
    if np.std(ra) < 1e-12 or np.std(rb) < 1e-12:
        return float("nan")
    return float(np.corrcoef(ra, rb)[0, 1])


def r2_score_np(y: np.ndarray, pred: np.ndarray) -> float:
    y = np.asarray(y, dtype=float)
    pred = np.asarray(pred, dtype=float)
    ss_res = float(np.sum((y - pred) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    if ss_tot < 1e-15:
        return float("nan")
    return 1.0 - ss_res / ss_tot


def normal_z_for_coverage(level: float) -> float:
    # central interval: P(-z <= Z <= z) = level
    p = torch.tensor((1.0 + float(level)) / 2.0, dtype=torch.float64)
    return float(torch.distributions.Normal(0.0, 1.0).icdf(p).item())


def objective_columns_from_details(
    details: pd.DataFrame,
    requested: Sequence[str],
) -> List[str]:
    cols = []
    for c in requested:
        if f"neighbor_{c}" in details.columns:
            cols.append(c)
    if not cols:
        raise ValueError(
            "No requested neighbor objective columns found. Expected columns like "
            "neighbor_chelation_sub in the corrected details CSV."
        )
    return cols


def find_peptide_col(df: pd.DataFrame, preferred: str = "peptide_len10") -> str:
    for c in [preferred, "peptide_len10", "sequence", "peptide"]:
        if c in df.columns:
            return c
    raise ValueError(f"No peptide column found. Available={list(df.columns)}")


# ============================================================================
# Latent-diffusion architecture (same as the user's trained model)
# ============================================================================

@dataclass
class ModelConfig:
    hidden_size: int = 64
    latent_dim: int = 64
    n_layers: int = 2
    dropout: float = 0.0
    decoder_conditioning: str = "concat_z_at_every_decoder_step"


@dataclass
class DiffusionConfig:
    hidden_dim: int = 128
    time_dim: int = 32
    n_blocks: int = 4
    train_steps: int = 100
    beta_start: float = 1e-4
    beta_end: float = 2e-2


class GRUEncoder(nn.Module):
    def __init__(
        self,
        hidden_size: int,
        latent_dim: int,
        n_layers: int,
        dropout: float,
    ):
        super().__init__()
        self.in_proj = nn.Linear(VOCAB, hidden_size)
        self.gru = nn.GRU(
            input_size=hidden_size,
            hidden_size=hidden_size,
            num_layers=n_layers,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0.0,
        )
        self.to_mu = nn.Linear(hidden_size, latent_dim)
        self.to_logvar = nn.Linear(hidden_size, latent_dim)

    def forward(self, x_onehot: torch.Tensor):
        h = self.in_proj(x_onehot)
        out_top, h_n = self.gru(h)
        h_last = h_n[-1]
        mu = self.to_mu(h_last)
        logvar = self.to_logvar(h_last).clamp(-8.0, 8.0)
        return mu, logvar, out_top


class LatentConditionedGRUDecoder(nn.Module):
    def __init__(
        self,
        hidden_size: int,
        latent_dim: int,
        n_layers: int,
        dropout: float,
    ):
        super().__init__()
        self.token_embed = nn.Linear(VOCAB, hidden_size)
        self.z_to_h = nn.Linear(latent_dim, n_layers * hidden_size)
        self.gru = nn.GRU(
            input_size=hidden_size + latent_dim,
            hidden_size=hidden_size,
            num_layers=n_layers,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0.0,
        )
        self.to_logits = nn.Linear(hidden_size, VOCAB)

    def initial_hidden(self, z: torch.Tensor) -> torch.Tensor:
        return self.z_to_h(z).view(
            self.gru.num_layers,
            z.size(0),
            self.gru.hidden_size,
        )

    def step(
        self,
        z: torch.Tensor,
        current_token: torch.Tensor,
        h: torch.Tensor,
    ):
        emb = self.token_embed(current_token)
        dec_input = torch.cat([emb, z.unsqueeze(1)], dim=-1)
        out, h = self.gru(dec_input, h)
        logits = self.to_logits(out[:, -1, :])
        return logits, h


class GRUVAE(nn.Module):
    def __init__(self, cfg: ModelConfig):
        super().__init__()
        self.cfg = cfg
        self.enc = GRUEncoder(
            cfg.hidden_size,
            cfg.latent_dim,
            cfg.n_layers,
            cfg.dropout,
        )
        self.dec = LatentConditionedGRUDecoder(
            cfg.hidden_size,
            cfg.latent_dim,
            cfg.n_layers,
            cfg.dropout,
        )


class SinusoidalTimeEmbedding(nn.Module):
    def __init__(self, dim: int):
        super().__init__()
        if dim % 2:
            raise ValueError("time_dim must be even")
        self.dim = int(dim)

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        half = self.dim // 2
        exponent = (
            -math.log(10000.0)
            * torch.arange(
                half,
                device=t.device,
                dtype=torch.float32,
            )
            / max(half - 1, 1)
        )
        frequencies = torch.exp(exponent)
        angles = t.float().unsqueeze(-1) * frequencies.unsqueeze(0)
        return torch.cat(
            [torch.sin(angles), torch.cos(angles)],
            dim=-1,
        )


class ResidualDenoiserBlock(nn.Module):
    def __init__(self, hidden_dim: int):
        super().__init__()
        self.norm = nn.LayerNorm(hidden_dim)
        self.fc1 = nn.Linear(hidden_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h = self.norm(x)
        h = F.silu(self.fc1(h))
        h = self.fc2(h)
        return x + h


class LatentDenoiser(nn.Module):
    def __init__(
        self,
        latent_dim: int,
        cfg: DiffusionConfig,
    ):
        super().__init__()
        self.time_embedding = SinusoidalTimeEmbedding(cfg.time_dim)
        self.time_mlp = nn.Sequential(
            nn.Linear(cfg.time_dim, cfg.hidden_dim),
            nn.SiLU(),
            nn.Linear(cfg.hidden_dim, cfg.hidden_dim),
        )
        self.in_proj = nn.Linear(latent_dim, cfg.hidden_dim)
        self.blocks = nn.ModuleList(
            [
                ResidualDenoiserBlock(cfg.hidden_dim)
                for _ in range(cfg.n_blocks)
            ]
        )
        self.out_norm = nn.LayerNorm(cfg.hidden_dim)
        self.out_proj = nn.Linear(cfg.hidden_dim, latent_dim)

    def forward(
        self,
        h_t: torch.Tensor,
        t: torch.Tensor,
    ) -> torch.Tensor:
        h = self.in_proj(h_t)
        h = h + self.time_mlp(self.time_embedding(t))
        for block in self.blocks:
            h = block(h)
        h = F.silu(self.out_norm(h))
        return self.out_proj(h)


class LatentDiffusion(nn.Module):
    def __init__(
        self,
        latent_dim: int,
        cfg: DiffusionConfig,
    ):
        super().__init__()
        self.latent_dim = int(latent_dim)
        self.cfg = cfg
        self.denoiser = LatentDenoiser(latent_dim, cfg)

        betas = torch.linspace(
            cfg.beta_start,
            cfg.beta_end,
            cfg.train_steps,
            dtype=torch.float32,
        )
        alphas = 1.0 - betas
        alpha_bars = torch.cumprod(alphas, dim=0)

        self.register_buffer("betas", betas)
        self.register_buffer("alphas", alphas)
        self.register_buffer("alpha_bars", alpha_bars)

    @torch.no_grad()
    def ddim_sample(
        self,
        base_noise: torch.Tensor,
        inference_steps: int = 20,
    ) -> torch.Tensor:
        self.eval()
        n_train = self.cfg.train_steps
        inference_steps = min(
            max(int(inference_steps), 1),
            n_train,
        )

        timesteps = (
            torch.linspace(
                n_train - 1,
                0,
                inference_steps,
                device=base_noise.device,
            )
            .round()
            .long()
        )
        timesteps = torch.unique_consecutive(timesteps)

        h = base_noise
        for step_index, t_scalar in enumerate(timesteps):
            t = torch.full(
                (h.size(0),),
                int(t_scalar.item()),
                device=h.device,
                dtype=torch.long,
            )
            pred_noise = self.denoiser(h, t)
            alpha_bar_t = self.alpha_bars[t_scalar]
            pred_h0 = (
                h
                - torch.sqrt(1.0 - alpha_bar_t) * pred_noise
            ) / torch.sqrt(alpha_bar_t)

            if step_index == len(timesteps) - 1:
                h = pred_h0
                break

            t_prev = timesteps[step_index + 1]
            alpha_bar_prev = self.alpha_bars[t_prev]
            h = (
                torch.sqrt(alpha_bar_prev) * pred_h0
                + torch.sqrt(1.0 - alpha_bar_prev) * pred_noise
            )

        return h

    @torch.no_grad()
    def ddim_invert(
        self,
        h0: torch.Tensor,
        inference_steps: int = 20,
    ) -> torch.Tensor:
        self.eval()
        n_train = self.cfg.train_steps
        inference_steps = min(
            max(int(inference_steps), 1),
            n_train,
        )
        timesteps = (
            torch.linspace(
                0,
                n_train - 1,
                inference_steps,
                device=h0.device,
            )
            .round()
            .long()
        )
        timesteps = torch.unique_consecutive(timesteps)

        h = h0
        for step_index, t_scalar in enumerate(timesteps[:-1]):
            t = torch.full(
                (h.size(0),),
                int(t_scalar.item()),
                device=h.device,
                dtype=torch.long,
            )
            pred_noise = self.denoiser(h, t)
            alpha_bar_t = self.alpha_bars[t_scalar]
            pred_h0 = (
                h
                - torch.sqrt(1.0 - alpha_bar_t) * pred_noise
            ) / torch.sqrt(alpha_bar_t)

            t_next = timesteps[step_index + 1]
            alpha_bar_next = self.alpha_bars[t_next]
            h = (
                torch.sqrt(alpha_bar_next) * pred_h0
                + torch.sqrt(1.0 - alpha_bar_next) * pred_noise
            )
        return h


def standardize_mu(
    mu: torch.Tensor,
    latent_mean: torch.Tensor,
    latent_std: torch.Tensor,
) -> torch.Tensor:
    return (
        mu - latent_mean.to(mu.device)
    ) / latent_std.to(mu.device).clamp(min=1e-6)


def project_to_radius(
    eps: torch.Tensor,
    radius: float,
) -> torch.Tensor:
    return (
        eps
        / eps.norm(dim=-1, keepdim=True).clamp(min=1e-8)
        * float(radius)
    )


@torch.no_grad()
def encode_standardized_h0(
    vae: GRUVAE,
    peptides: Sequence[str],
    latent_mean: torch.Tensor,
    latent_std: torch.Tensor,
    device: torch.device,
    batch_size: int = 256,
) -> np.ndarray:
    chunks = []
    x_all = onehot_encode_peptides(peptides)
    for start in range(0, len(peptides), batch_size):
        x = x_all[start : start + batch_size].to(device)
        mu, _, _ = vae.enc(x)
        h0 = standardize_mu(
            mu,
            latent_mean,
            latent_std,
        )
        chunks.append(h0.cpu())
    return torch.cat(chunks, dim=0).numpy()


# ============================================================================
# Reconstruct the exact corrected epsilon-neighbor sample set
# ============================================================================

def load_models(
    checkpoint_path: str,
    device: torch.device,
):
    ckpt = torch.load(checkpoint_path, map_location=device)

    mc = ckpt["model_config"]
    dc = ckpt["diffusion_config"]

    cfg = ModelConfig(
        hidden_size=int(mc["hidden_size"]),
        latent_dim=int(mc["latent_dim"]),
        n_layers=int(mc["n_layers"]),
        dropout=float(mc.get("dropout", 0.0)),
        decoder_conditioning=str(
            mc.get(
                "decoder_conditioning",
                "concat_z_at_every_decoder_step",
            )
        ),
    )

    diff_cfg = DiffusionConfig(
        hidden_dim=int(dc["hidden_dim"]),
        time_dim=int(dc["time_dim"]),
        n_blocks=int(dc["n_blocks"]),
        train_steps=int(dc["train_steps"]),
        beta_start=float(dc["beta_start"]),
        beta_end=float(dc["beta_end"]),
    )

    vae = GRUVAE(cfg).to(device)
    diffusion = LatentDiffusion(cfg.latent_dim, diff_cfg).to(device)

    vae.load_state_dict(
        ckpt["vae_state_dict"],
        strict=True,
    )
    diffusion.load_state_dict(
        ckpt["diffusion_state_dict"],
        strict=True,
    )

    vae.eval()
    diffusion.eval()

    latent_mean = ckpt["latent_mean"].to(device).float()
    latent_std = (
        ckpt["latent_std"]
        .to(device)
        .float()
        .clamp(min=1e-6)
    )

    return ckpt, cfg, vae, diffusion, latent_mean, latent_std


def select_source_centers(
    cu_df: pd.DataFrame,
    peptide_col: str,
    objective_cols: Sequence[str],
    n_centers: int,
    center_selection: str,
    rank_objective: str,
    seed: int,
) -> List[Tuple[int, str]]:
    valid = []
    for idx, row in cu_df.iterrows():
        pep = clean_peptide(row[peptide_col])
        if pep is None:
            continue
        if any(pd.isna(row[c]) for c in objective_cols):
            continue
        valid.append((idx, pep))

    if not valid:
        raise ValueError("No valid source peptides.")

    n_centers = min(int(n_centers), len(valid))
    rng = np.random.default_rng(seed)

    if center_selection == "random":
        ids = rng.choice(
            len(valid),
            size=n_centers,
            replace=False,
        )
        return [valid[int(i)] for i in ids]

    rank_col = (
        rank_objective
        if rank_objective in cu_df.columns
        else objective_cols[0]
    )

    ranked = sorted(
        [
            (
                float(cu_df.loc[idx, rank_col]),
                idx,
                pep,
            )
            for idx, pep in valid
        ],
        reverse=True,
    )
    return [
        (idx, pep)
        for _, idx, pep in ranked[:n_centers]
    ]


@torch.no_grad()
def reconstruct_gp_dataset(
    args: argparse.Namespace,
    objective_cols: Sequence[str],
    device: torch.device,
):
    ckpt, cfg, vae, diffusion, latent_mean, latent_std = load_models(
        args.checkpoint,
        device,
    )

    cu_df = pd.read_csv(args.cu_csv)
    peptide_col = find_peptide_col(
        cu_df,
        args.peptide_col,
    )

    selected = select_source_centers(
        cu_df=cu_df,
        peptide_col=peptide_col,
        objective_cols=objective_cols,
        n_centers=args.n_centers,
        center_selection=args.center_selection,
        rank_objective=args.rank_objective,
        seed=args.sample_seed,
    )

    source_peptides = [pep for _, pep in selected]
    x_centers = onehot_encode_peptides(
        source_peptides
    ).to(device)

    mu, _, _ = vae.enc(x_centers)
    h0_source = standardize_mu(
        mu,
        latent_mean,
        latent_std,
    )

    eps_centers = diffusion.ddim_invert(
        h0_source,
        inference_steps=args.ddim_steps,
    )

    radius = (
        float(args.radius)
        if args.radius is not None
        else math.sqrt(cfg.latent_dim)
    )

    if args.project_centers_to_sphere:
        eps_centers = project_to_radius(
            eps_centers,
            radius,
        )

    h_centers = diffusion.ddim_sample(
        eps_centers,
        inference_steps=args.ddim_steps,
    )

    details = pd.read_csv(
        args.corrected_neighbor_details_csv
    )

    required_id_cols = [
        "center_index",
        "sigma",
        "neighbor_index",
        "neighbor_peptide",
    ]
    missing_id = [
        c for c in required_id_cols
        if c not in details.columns
    ]
    if missing_id:
        raise ValueError(
            f"Corrected details CSV missing columns: {missing_id}"
        )

    # Index rows by deterministic generation identity.
    detail_lookup = {}
    for _, row in details.iterrows():
        key = (
            int(row["center_index"]),
            round(float(row["sigma"]), 12),
            int(row["neighbor_index"]),
        )
        detail_lookup[key] = row

    gen = torch.Generator(device="cpu")
    gen.manual_seed(int(args.sample_seed) + 1234)

    rows = []
    eps_vectors = []
    h_ddim_vectors = []

    for i, src in enumerate(source_peptides):
        eps0 = eps_centers[i : i + 1]

        for sigma in args.sigmas:
            for j in range(args.neighbors_per_sigma):
                noise = (
                    torch.randn(
                        eps0.shape,
                        generator=gen,
                        device="cpu",
                        dtype=torch.float32,
                    )
                    .to(device)
                    * float(sigma)
                )

                eps1 = eps0 + noise
                if args.renormalize_neighbors:
                    eps1 = project_to_radius(
                        eps1,
                        radius,
                    )

                h1 = diffusion.ddim_sample(
                    eps1,
                    inference_steps=args.ddim_steps,
                )

                key = (
                    i,
                    round(float(sigma), 12),
                    j,
                )
                if key not in detail_lookup:
                    raise KeyError(
                        f"No corrected-details row for {key}"
                    )

                drow = detail_lookup[key]
                pep = clean_peptide(
                    drow["neighbor_peptide"]
                )
                if pep is None:
                    raise ValueError(
                        f"Invalid neighbor peptide for {key}: "
                        f"{drow['neighbor_peptide']!r}"
                    )

                y = {}
                for c in objective_cols:
                    col = f"neighbor_{c}"
                    if col not in details.columns:
                        raise ValueError(
                            f"Missing objective column: {col}"
                        )
                    value = float(drow[col])
                    if not np.isfinite(value):
                        raise ValueError(
                            f"Non-finite {col} for {key}"
                        )
                    y[c] = value

                rows.append(
                    {
                        "point_type": "neighbor",
                        "center_index": i,
                        "source_peptide": src,
                        "peptide_len10": pep,
                        "sigma": float(sigma),
                        "neighbor_index": int(j),
                        **y,
                    }
                )
                eps_vectors.append(
                    eps1.squeeze(0).detach().cpu().numpy()
                )
                h_ddim_vectors.append(
                    h1.squeeze(0).detach().cpu().numpy()
                )

    meta = pd.DataFrame(rows)
    X_eps = np.vstack(eps_vectors)
    X_h_ddim = np.vstack(h_ddim_vectors)

    # Direct VAE encoder h0 of the evaluated decoded peptide.
    X_h_encoded = encode_standardized_h0(
        vae,
        meta["peptide_len10"].tolist(),
        latent_mean,
        latent_std,
        device,
        batch_size=args.encode_batch_size,
    )

    # Optional decoded centers.
    if args.include_centers and args.decoded_centers_csv:
        center_df = pd.read_csv(
            args.decoded_centers_csv
        )

        center_rows = []
        center_eps = []
        center_h_ddim = []

        for _, row in center_df.iterrows():
            i = int(row["center_index"])
            pep = clean_peptide(
                row["center_decoded_peptide"]
            )
            if pep is None:
                continue

            y = {}
            complete = True
            for c in objective_cols:
                col = f"center_decoded_{c}"
                if col not in center_df.columns:
                    complete = False
                    break
                value = pd.to_numeric(
                    pd.Series([row[col]]),
                    errors="coerce",
                ).iloc[0]
                if pd.isna(value):
                    complete = False
                    break
                y[c] = float(value)

            if not complete:
                continue

            center_rows.append(
                {
                    "point_type": "center",
                    "center_index": i,
                    "source_peptide": source_peptides[i],
                    "peptide_len10": pep,
                    "sigma": 0.0,
                    "neighbor_index": -1,
                    **y,
                }
            )
            center_eps.append(
                eps_centers[i].detach().cpu().numpy()
            )
            center_h_ddim.append(
                h_centers[i].detach().cpu().numpy()
            )

        if center_rows:
            cmeta = pd.DataFrame(center_rows)
            chenc = encode_standardized_h0(
                vae,
                cmeta["peptide_len10"].tolist(),
                latent_mean,
                latent_std,
                device,
                batch_size=args.encode_batch_size,
            )

            meta = pd.concat(
                [meta, cmeta],
                ignore_index=True,
            )
            X_eps = np.vstack(
                [X_eps, np.vstack(center_eps)]
            )
            X_h_ddim = np.vstack(
                [X_h_ddim, np.vstack(center_h_ddim)]
            )
            X_h_encoded = np.vstack(
                [X_h_encoded, chenc]
            )

    representations = {
        "diffusion_epsilon": X_eps.astype(np.float64),
        "vae_h0_ddim": X_h_ddim.astype(np.float64),
        "vae_h0_encoded": X_h_encoded.astype(np.float64),
    }

    return (
        meta.reset_index(drop=True),
        representations,
        {
            "checkpoint_epoch": ckpt.get("epoch"),
            "checkpoint_selection": ckpt.get(
                "checkpoint_selection"
            ),
            "latent_dim": cfg.latent_dim,
            "radius": radius,
        },
    )


# ============================================================================
# Optional RealNVP coordinate loading
# ============================================================================

def detect_realnvp_columns(
    df: pd.DataFrame,
    explicit_prefix: str,
) -> List[str]:
    if explicit_prefix:
        cols = [
            c for c in df.columns
            if str(c).startswith(explicit_prefix)
        ]
        if not cols:
            raise ValueError(
                f"No RealNVP columns start with "
                f"{explicit_prefix!r}"
            )
        return sorted(cols)

    prefixes = [
        "zK_",
        "zk_",
        "zK",
        "flow_",
        "postflow_",
        "post_flow_",
        "latent_flow_",
    ]

    candidates = []
    for prefix in prefixes:
        cols = [
            c for c in df.columns
            if str(c).startswith(prefix)
            and pd.api.types.is_numeric_dtype(df[c])
        ]
        if len(cols) >= 2:
            candidates.append((len(cols), prefix, sorted(cols)))

    if not candidates:
        # Last-resort numeric latent-ish columns.
        cols = [
            c for c in df.columns
            if pd.api.types.is_numeric_dtype(df[c])
            and any(
                token in str(c).lower()
                for token in ["zk", "flow"]
            )
        ]
        if len(cols) >= 2:
            return sorted(cols)

        raise ValueError(
            "Could not auto-detect RealNVP post-flow columns. "
            "Pass --realnvp-prefix explicitly."
        )

    candidates.sort(reverse=True)
    return candidates[0][2]


def add_realnvp_representation(
    meta: pd.DataFrame,
    representations: Dict[str, np.ndarray],
    csv_path: str,
    peptide_col_preferred: str,
    prefix: str,
):
    if not csv_path:
        return meta, representations

    rdf = pd.read_csv(csv_path)
    pep_col = find_peptide_col(
        rdf,
        peptide_col_preferred,
    )
    cols = detect_realnvp_columns(
        rdf,
        prefix,
    )

    rdf = rdf.copy()
    rdf["_pep"] = rdf[pep_col].map(clean_peptide)
    rdf = rdf.dropna(subset=["_pep"]).copy()
    rdf = rdf.drop_duplicates(
        "_pep",
        keep="first",
    )

    lookup = {
        p: row[cols].to_numpy(dtype=float)
        for p, (_, row) in zip(
            rdf["_pep"].tolist(),
            rdf.iterrows(),
        )
    }

    keep = np.array(
        [
            p in lookup
            for p in meta["peptide_len10"]
        ],
        dtype=bool,
    )

    n_before = len(meta)
    meta2 = meta.loc[keep].reset_index(drop=True)

    reps2 = {
        name: X[keep]
        for name, X in representations.items()
    }

    X_flow = np.vstack(
        [
            lookup[p]
            for p in meta2["peptide_len10"]
        ]
    ).astype(np.float64)

    reps2["realnvp"] = X_flow

    print(
        f"RealNVP common-point intersection: "
        f"{len(meta2)}/{n_before}; "
        f"flow_dim={X_flow.shape[1]}"
    )

    return meta2, reps2


# ============================================================================
# Grouped train/test splits
# ============================================================================

def make_grouped_split(
    meta: pd.DataFrame,
    test_fraction: float,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)

    groups = np.array(
        sorted(
            meta["peptide_len10"]
            .astype(str)
            .unique()
            .tolist()
        )
    )

    rng.shuffle(groups)

    n_test_groups = max(
        1,
        int(round(len(groups) * float(test_fraction))),
    )
    test_groups = set(
        groups[:n_test_groups].tolist()
    )

    test_mask = (
        meta["peptide_len10"]
        .astype(str)
        .isin(test_groups)
        .to_numpy()
    )

    test_idx = np.flatnonzero(test_mask)
    train_idx = np.flatnonzero(~test_mask)

    if len(test_idx) < 2 or len(train_idx) < 4:
        raise ValueError(
            f"Grouped split too small: train={len(train_idx)}, "
            f"test={len(test_idx)}"
        )

    return train_idx, test_idx


def nested_training_indices(
    train_pool_idx: np.ndarray,
    sizes: Sequence[int],
    seed: int,
) -> Dict[int, np.ndarray]:
    rng = np.random.default_rng(seed)
    order = np.asarray(train_pool_idx).copy()
    rng.shuffle(order)

    out = {}
    for requested in sorted(set(int(s) for s in sizes)):
        n = min(requested, len(order))
        if n < 4:
            continue
        out[requested] = order[:n].copy()
    return out


# ============================================================================
# GP model, fitting, prediction and metrics
# ============================================================================

def standardize_X_train_test(
    X_train: np.ndarray,
    X_test: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    mu = np.mean(X_train, axis=0)
    std = np.std(X_train, axis=0)
    std = np.where(std < 1e-8, 1.0, std)
    return (
        (X_train - mu) / std,
        (X_test - mu) / std,
        mu,
        std,
    )


def build_gp(
    train_X: torch.Tensor,
    train_Y: torch.Tensor,
    kernel: str,
    ard: bool,
) -> SingleTaskGP:
    d = train_X.shape[-1]
    ard_dims = d if ard else None

    if kernel == "rbf":
        base = RBFKernel(
            ard_num_dims=ard_dims,
        )
    else:
        base = MaternKernel(
            nu=2.5,
            ard_num_dims=ard_dims,
        )

    covar = ScaleKernel(base)

    model = SingleTaskGP(
        train_X=train_X,
        train_Y=train_Y,
        covar_module=covar,
        outcome_transform=Standardize(m=1),
    )
    return model


def fit_single_gp(
    X_train: np.ndarray,
    y_train: np.ndarray,
    device: torch.device,
    dtype: torch.dtype,
    kernel: str,
    ard: bool,
    max_fit_attempts: int,
) -> SingleTaskGP:
    train_X = torch.tensor(
        X_train,
        device=device,
        dtype=dtype,
    )
    train_Y = torch.tensor(
        y_train.reshape(-1, 1),
        device=device,
        dtype=dtype,
    )

    last_exc = None

    for attempt in range(max(1, int(max_fit_attempts))):
        try:
            model = build_gp(
                train_X,
                train_Y,
                kernel,
                ard,
            ).to(device=device, dtype=dtype)

            mll = ExactMarginalLogLikelihood(
                model.likelihood,
                model,
            )

            # BoTorch handles the optimizer details and constraints.
            fit_gpytorch_mll(mll)
            model.eval()
            model.likelihood.eval()
            return model

        except Exception as exc:
            last_exc = exc
            warnings.warn(
                f"GP fit attempt {attempt + 1} failed: {exc}"
            )
            if device.type == "cuda":
                torch.cuda.empty_cache()

    raise RuntimeError(
        f"GP fitting failed after {max_fit_attempts} attempts"
    ) from last_exc


@torch.no_grad()
def gp_predict(
    model: SingleTaskGP,
    X_test: np.ndarray,
    device: torch.device,
    dtype: torch.dtype,
) -> Tuple[np.ndarray, np.ndarray]:
    tx = torch.tensor(
        X_test,
        device=device,
        dtype=dtype,
    )

    # observation_noise=True makes NLPD / predictive interval coverage evaluate
    # the predictive distribution for observations, not only latent f(x).
    posterior = model.posterior(
        tx,
        observation_noise=True,
    )

    mean = (
        posterior.mean
        .squeeze(-1)
        .detach()
        .cpu()
        .numpy()
    )
    var = (
        posterior.variance
        .squeeze(-1)
        .clamp(min=1e-12)
        .detach()
        .cpu()
        .numpy()
    )
    return mean, var


def predictive_metrics(
    y: np.ndarray,
    mean: np.ndarray,
    var: np.ndarray,
) -> Dict[str, float]:
    y = np.asarray(y, dtype=float)
    mean = np.asarray(mean, dtype=float)
    var = np.maximum(
        np.asarray(var, dtype=float),
        1e-12,
    )

    err = mean - y
    rmse = float(np.sqrt(np.mean(err ** 2)))
    mae = float(np.mean(np.abs(err)))
    r2 = r2_score_np(y, mean)
    spearman = spearman_safe(y, mean)

    nlpd_each = 0.5 * (
        np.log(2.0 * np.pi * var)
        + ((y - mean) ** 2) / var
    )
    nlpd = float(np.mean(nlpd_each))

    sd = np.sqrt(var)
    zres = (y - mean) / sd

    coverage = {}
    calibration_abs_errors = []
    for level in [0.50, 0.80, 0.90, 0.95]:
        z = normal_z_for_coverage(level)
        inside = np.abs(y - mean) <= z * sd
        cov = float(np.mean(inside))
        coverage[level] = cov
        calibration_abs_errors.append(
            abs(cov - level)
        )

    return {
        "rmse": rmse,
        "mae": mae,
        "r2": r2,
        "spearman": spearman,
        "nlpd": nlpd,
        "coverage_50": coverage[0.50],
        "coverage_80": coverage[0.80],
        "coverage_90": coverage[0.90],
        "coverage_95": coverage[0.95],
        "coverage95_abs_error": abs(
            coverage[0.95] - 0.95
        ),
        "calibration_ece": float(
            np.mean(calibration_abs_errors)
        ),
        "standardized_residual_mean": float(
            np.mean(zres)
        ),
        "standardized_residual_std": float(
            np.std(zres)
        ),
        "mean_predictive_sd": float(
            np.mean(sd)
        ),
    }


# ============================================================================
# Benchmark
# ============================================================================

def run_benchmark(args: argparse.Namespace) -> None:
    set_seed(args.sample_seed)

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device(args.device)
    dtype = (
        torch.float64
        if args.dtype == "float64"
        else torch.float32
    )

    # Determine objectives from corrected details.
    details_probe = pd.read_csv(
        args.corrected_neighbor_details_csv,
        nrows=5,
    )
    objective_cols = objective_columns_from_details(
        details_probe,
        args.objective_cols,
    )

    print("=" * 88)
    print("GP REPRESENTATION VALIDATION")
    print("=" * 88)
    print(f"Device: {device}")
    print(f"dtype: {dtype}")
    print(f"Objectives: {objective_cols}")

    meta, representations, latent_info = reconstruct_gp_dataset(
        args,
        objective_cols,
        device,
    )

    if args.realnvp_coordinates_csv:
        meta, representations = add_realnvp_representation(
            meta,
            representations,
            args.realnvp_coordinates_csv,
            args.peptide_col,
            args.realnvp_prefix,
        )

    # Remove rows with any nonfinite objective.
    Y = meta[objective_cols].to_numpy(dtype=float)
    finite = np.isfinite(Y).all(axis=1)

    meta = meta.loc[finite].reset_index(drop=True)
    representations = {
        name: X[finite]
        for name, X in representations.items()
    }
    Y = meta[objective_cols].to_numpy(dtype=float)

    if len(meta) < 30:
        raise ValueError(
            f"Too few valid rows for GP validation: {len(meta)}"
        )

    print(f"Common evaluated points: {len(meta)}")
    print(
        f"Unique decoded peptides: "
        f"{meta['peptide_len10'].nunique()}"
    )
    for name, X in representations.items():
        print(
            f"Representation {name}: shape={X.shape}"
        )

    # Save reconstructed dataset metadata and all coordinates separately.
    meta.to_csv(
        out_dir / "gp_validation_points.csv",
        index=False,
    )

    for name, X in representations.items():
        np.save(
            out_dir / f"coordinates_{name}.npy",
            X,
        )

    all_metrics = []
    prediction_rows = []

    for split_seed in args.split_seeds:
        train_pool_idx, test_idx = make_grouped_split(
            meta,
            args.test_fraction,
            int(split_seed),
        )

        nested = nested_training_indices(
            train_pool_idx,
            args.train_sizes,
            int(split_seed) + 9001,
        )

        print()
        print(
            f"Split seed={split_seed}: "
            f"train_pool={len(train_pool_idx)}, "
            f"test={len(test_idx)}, "
            f"test_unique_peptides="
            f"{meta.iloc[test_idx]['peptide_len10'].nunique()}"
        )

        for requested_size, train_idx in nested.items():
            actual_size = len(train_idx)
            print(
                f"  train_size={actual_size} "
                f"(requested {requested_size})"
            )

            y_test_all = Y[test_idx]

            for rep_name, X in representations.items():
                X_train_raw = X[train_idx]
                X_test_raw = X[test_idx]

                (
                    X_train,
                    X_test,
                    xmean,
                    xstd,
                ) = standardize_X_train_test(
                    X_train_raw,
                    X_test_raw,
                )

                for obj_j, objective in enumerate(
                    objective_cols
                ):
                    y_train = Y[train_idx, obj_j]
                    y_test = y_test_all[:, obj_j]

                    print(
                        f"    {rep_name:20s} "
                        f"{objective:18s}",
                        end=" ",
                        flush=True,
                    )

                    try:
                        model = fit_single_gp(
                            X_train,
                            y_train,
                            device,
                            dtype,
                            args.kernel,
                            args.ard,
                            args.max_fit_attempts,
                        )

                        pred_mean, pred_var = gp_predict(
                            model,
                            X_test,
                            device,
                            dtype,
                        )

                        metrics = predictive_metrics(
                            y_test,
                            pred_mean,
                            pred_var,
                        )

                        row = {
                            "split_seed": int(split_seed),
                            "requested_train_size": int(
                                requested_size
                            ),
                            "train_size": int(actual_size),
                            "test_size": int(len(test_idx)),
                            "representation": rep_name,
                            "dimension": int(X.shape[1]),
                            "objective": objective,
                            "kernel": args.kernel,
                            "ard": bool(args.ard),
                            **metrics,
                        }
                        all_metrics.append(row)

                        print(
                            f"RMSE={metrics['rmse']:.4f} "
                            f"R2={metrics['r2']:.3f} "
                            f"NLPD={metrics['nlpd']:.3f} "
                            f"Cov95={metrics['coverage_95']:.3f}"
                        )

                        if args.save_predictions:
                            for local_k, global_idx in enumerate(
                                test_idx
                            ):
                                prediction_rows.append(
                                    {
                                        "split_seed": int(
                                            split_seed
                                        ),
                                        "train_size": int(
                                            actual_size
                                        ),
                                        "representation": rep_name,
                                        "objective": objective,
                                        "row_index": int(
                                            global_idx
                                        ),
                                        "peptide_len10": meta.iloc[
                                            global_idx
                                        ]["peptide_len10"],
                                        "y_true": float(
                                            y_test[local_k]
                                        ),
                                        "pred_mean": float(
                                            pred_mean[local_k]
                                        ),
                                        "pred_var": float(
                                            pred_var[local_k]
                                        ),
                                        "pred_sd": float(
                                            math.sqrt(
                                                max(
                                                    pred_var[
                                                        local_k
                                                    ],
                                                    1e-12,
                                                )
                                            )
                                        ),
                                    }
                                )

                        del model
                        if device.type == "cuda":
                            torch.cuda.empty_cache()

                    except Exception as exc:
                        print(f"FAILED: {type(exc).__name__}: {exc}")
                        all_metrics.append(
                            {
                                "split_seed": int(split_seed),
                                "requested_train_size": int(
                                    requested_size
                                ),
                                "train_size": int(actual_size),
                                "test_size": int(len(test_idx)),
                                "representation": rep_name,
                                "dimension": int(X.shape[1]),
                                "objective": objective,
                                "kernel": args.kernel,
                                "ard": bool(args.ard),
                                "fit_error": (
                                    f"{type(exc).__name__}: {exc}"
                                ),
                            }
                        )

    metrics_df = pd.DataFrame(all_metrics)
    metrics_path = out_dir / "gp_validation_metrics_long.csv"
    metrics_df.to_csv(
        metrics_path,
        index=False,
    )

    if args.save_predictions and prediction_rows:
        pd.DataFrame(prediction_rows).to_csv(
            out_dir / "gp_validation_predictions.csv",
            index=False,
        )

    good = metrics_df[
        metrics_df["rmse"].notna()
    ].copy()

    if good.empty:
        raise RuntimeError(
            "No GP fits completed successfully."
        )

    metric_cols = [
        "rmse",
        "mae",
        "r2",
        "spearman",
        "nlpd",
        "coverage_50",
        "coverage_80",
        "coverage_90",
        "coverage_95",
        "coverage95_abs_error",
        "calibration_ece",
        "standardized_residual_mean",
        "standardized_residual_std",
        "mean_predictive_sd",
    ]

    summary = (
        good.groupby(
            [
                "representation",
                "dimension",
                "objective",
                "train_size",
            ],
            dropna=False,
        )[metric_cols]
        .agg(["mean", "std"])
        .reset_index()
    )

    # Flatten MultiIndex columns.
    summary.columns = [
        (
            "_".join(
                str(x)
                for x in col
                if str(x) not in {"", "None"}
            )
            if isinstance(col, tuple)
            else str(col)
        )
        for col in summary.columns
    ]

    summary_path = (
        out_dir
        / "gp_validation_learning_curve_summary.csv"
    )
    summary.to_csv(
        summary_path,
        index=False,
    )

    # Full-size aggregate ranking across objectives and seeds.
    max_size = int(good["train_size"].max())
    full = good[
        good["train_size"] == max_size
    ].copy()

    ranking = (
        full.groupby(
            ["representation", "dimension"]
        )
        .agg(
            mean_rmse=("rmse", "mean"),
            mean_mae=("mae", "mean"),
            mean_r2=("r2", "mean"),
            mean_spearman=("spearman", "mean"),
            mean_nlpd=("nlpd", "mean"),
            mean_calibration_ece=(
                "calibration_ece",
                "mean",
            ),
            mean_coverage95_abs_error=(
                "coverage95_abs_error",
                "mean",
            ),
        )
        .reset_index()
        .sort_values(
            [
                "mean_rmse",
                "mean_nlpd",
                "mean_calibration_ece",
            ]
        )
    )

    ranking.to_csv(
        out_dir
        / "gp_validation_representation_ranking.csv",
        index=False,
    )

    make_learning_curve_plots(
        good,
        objective_cols,
        out_dir,
    )

    make_calibration_plot(
        good,
        max_size,
        out_dir,
    )

    report = build_report(
        args,
        meta,
        representations,
        latent_info,
        good,
        ranking,
        max_size,
        objective_cols,
    )

    report_path = (
        out_dir
        / "gp_validation_report.txt"
    )
    report_path.write_text(
        report,
        encoding="utf-8",
    )

    print()
    print(report)
    print()
    print(f"Saved long metrics: {metrics_path}")
    print(f"Saved learning summary: {summary_path}")
    print(
        "Saved representation ranking: "
        f"{out_dir / 'gp_validation_representation_ranking.csv'}"
    )
    print(f"Saved report: {report_path}")


# ============================================================================
# Reporting / plots
# ============================================================================

def make_learning_curve_plots(
    good: pd.DataFrame,
    objective_cols: Sequence[str],
    out_dir: Path,
) -> None:
    for metric in ["rmse", "r2", "nlpd", "calibration_ece"]:
        for objective in objective_cols:
            g = good[
                good["objective"] == objective
            ]
            if g.empty:
                continue

            plt.figure(figsize=(8, 5))

            for rep, rg in g.groupby(
                "representation"
            ):
                agg = (
                    rg.groupby("train_size")[metric]
                    .agg(["mean", "std"])
                    .reset_index()
                    .sort_values("train_size")
                )
                x = agg["train_size"].to_numpy()
                y = agg["mean"].to_numpy()
                s = agg["std"].fillna(0.0).to_numpy()

                plt.plot(
                    x,
                    y,
                    marker="o",
                    label=rep,
                )
                plt.fill_between(
                    x,
                    y - s,
                    y + s,
                    alpha=0.15,
                )

            plt.xlabel("GP training size")
            plt.ylabel(metric)
            plt.title(
                f"{objective}: GP {metric} vs training size"
            )
            plt.legend()
            plt.tight_layout()
            plt.savefig(
                out_dir
                / f"learning_curve_{objective}_{metric}.png",
                dpi=180,
            )
            plt.close()


def make_calibration_plot(
    good: pd.DataFrame,
    max_size: int,
    out_dir: Path,
) -> None:
    g = good[
        good["train_size"] == max_size
    ].copy()
    if g.empty:
        return

    nominal = np.array(
        [0.50, 0.80, 0.90, 0.95],
        dtype=float,
    )

    plt.figure(figsize=(7, 6))

    for rep, rg in g.groupby("representation"):
        empirical = np.array(
            [
                rg["coverage_50"].mean(),
                rg["coverage_80"].mean(),
                rg["coverage_90"].mean(),
                rg["coverage_95"].mean(),
            ]
        )
        plt.plot(
            nominal,
            empirical,
            marker="o",
            label=rep,
        )

    plt.plot(
        [0.45, 1.0],
        [0.45, 1.0],
        linestyle="--",
        label="ideal",
    )
    plt.xlabel("Nominal predictive interval coverage")
    plt.ylabel("Empirical coverage")
    plt.title(
        f"GP uncertainty calibration at n={max_size}"
    )
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        out_dir
        / "uncertainty_calibration_full_size.png",
        dpi=180,
    )
    plt.close()


def build_report(
    args: argparse.Namespace,
    meta: pd.DataFrame,
    representations: Dict[str, np.ndarray],
    latent_info: Dict[str, object],
    good: pd.DataFrame,
    ranking: pd.DataFrame,
    max_size: int,
    objective_cols: Sequence[str],
) -> str:
    lines = []
    lines.append(
        "GP SURROGATE REPRESENTATION VALIDATION REPORT"
    )
    lines.append("=" * 80)
    lines.append(
        f"checkpoint={args.checkpoint}"
    )
    lines.append(
        f"checkpoint_epoch={latent_info.get('checkpoint_epoch')}"
    )
    lines.append(
        f"checkpoint_selection={latent_info.get('checkpoint_selection')}"
    )
    lines.append(
        f"n_evaluated_coordinate_points={len(meta)}"
    )
    lines.append(
        f"n_unique_decoded_peptides={meta['peptide_len10'].nunique()}"
    )
    lines.append(
        f"objectives={list(objective_cols)}"
    )
    lines.append(
        f"representations={list(representations.keys())}"
    )
    lines.append(
        f"split_seeds={list(args.split_seeds)}"
    )
    lines.append(
        f"test_fraction={args.test_fraction}"
    )
    lines.append(
        f"train_sizes={list(args.train_sizes)}"
    )
    lines.append(
        f"kernel={args.kernel}, ard={args.ard}"
    )
    lines.append(
        "split_mode=decoded_peptide_grouped_no_identical_peptide_leakage"
    )
    lines.append("")

    lines.append(
        f"FULL-SIZE COMPARISON (train_size={max_size})"
    )
    lines.append("-" * 80)

    for _, row in ranking.iterrows():
        lines.append(
            f"{row['representation']}: "
            f"dim={int(row['dimension'])}, "
            f"mean_RMSE={row['mean_rmse']:.6f}, "
            f"mean_MAE={row['mean_mae']:.6f}, "
            f"mean_R2={row['mean_r2']:.6f}, "
            f"mean_Spearman={row['mean_spearman']:.6f}, "
            f"mean_NLPD={row['mean_nlpd']:.6f}, "
            f"mean_calibration_ECE={row['mean_calibration_ece']:.6f}, "
            f"mean_95pct_coverage_error="
            f"{row['mean_coverage95_abs_error']:.6f}"
        )

    lines.append("")
    lines.append(
        "PER-OBJECTIVE FULL-SIZE RESULTS"
    )
    lines.append("-" * 80)

    full = good[
        good["train_size"] == max_size
    ]

    agg = (
        full.groupby(
            ["representation", "objective"]
        )
        .agg(
            rmse=("rmse", "mean"),
            mae=("mae", "mean"),
            r2=("r2", "mean"),
            spearman=("spearman", "mean"),
            nlpd=("nlpd", "mean"),
            coverage95=("coverage_95", "mean"),
            calibration_ece=(
                "calibration_ece",
                "mean",
            ),
        )
        .reset_index()
    )

    for rep in agg["representation"].unique():
        lines.append(f"[{rep}]")
        rg = agg[
            agg["representation"] == rep
        ]
        for _, r in rg.iterrows():
            lines.append(
                f"  {r['objective']}: "
                f"RMSE={r['rmse']:.5f}, "
                f"MAE={r['mae']:.5f}, "
                f"R2={r['r2']:.4f}, "
                f"Spearman={r['spearman']:.4f}, "
                f"NLPD={r['nlpd']:.4f}, "
                f"Cov95={r['coverage95']:.4f}, "
                f"CalECE={r['calibration_ece']:.4f}"
            )

    lines.append("")
    lines.append(
        "INTERPRETATION"
    )
    lines.append("-" * 80)
    lines.append(
        "- Lower RMSE/MAE/NLPD/calibration ECE are better."
    )
    lines.append(
        "- Higher R2 and Spearman are better."
    )
    lines.append(
        "- 95% predictive coverage should be near 0.95; "
        "coverage alone is not enough because excessively wide uncertainty "
        "can be trivially over-conservative."
    )
    lines.append(
        "- A representation that is consistently better across objectives, "
        "split seeds and training sizes is the stronger GP surrogate space."
    )
    lines.append(
        "- For qEHVI, prioritize predictive ranking, calibrated uncertainty, "
        "and stable learning curves rather than one metric alone."
    )
    lines.append(
        "- If diffusion_epsilon matches or beats h0 on RMSE/R2/Spearman and "
        "has comparable or better NLPD/calibration, that supports a full GO "
        "for epsilon-space GP/qEHVI."
    )

    return "\n".join(lines) + "\n"


# ============================================================================
# CLI
# ============================================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Compare exact-GP learnability of VAE h0, diffusion epsilon, "
            "and optional RealNVP coordinates using the same black-box-scored "
            "epsilon sample points."
        )
    )

    p.add_argument(
        "--checkpoint",
        default=(
            "../../output/"
            "finetuned_gru_vae_latent_diffusion_checkpoints_h64_z64_high_confidence_dataset/"
            "best_ddim_inversion_l2_h64_z64_latent_diffusion.pt"
        ),
    )

    p.add_argument(
        "--cu-csv",
        default=(
            "../../data/"
            "metalpdb_CU_chain_mapped_len10_high_confidence_blackbox_scored_ranked.csv"
        ),
    )

    p.add_argument(
        "--corrected-neighbor-details-csv",
        default=(
            "../../output/"
            "epsilon_objective_smoothness_diagnostic_corrected/"
            "epsilon_objective_neighbor_details_corrected.csv"
        ),
    )

    p.add_argument(
        "--decoded-centers-csv",
        default=(
            "../../output/"
            "epsilon_objective_smoothness_diagnostic_corrected/"
            "epsilon_decoded_centers.csv"
        ),
    )

    p.add_argument(
        "--include-centers",
        action="store_true",
        default=True,
    )
    p.add_argument(
        "--no-include-centers",
        dest="include_centers",
        action="store_false",
    )

    p.add_argument(
        "--peptide-col",
        default="peptide_len10",
    )

    p.add_argument(
        "--objective-cols",
        nargs="+",
        default=DEFAULT_OBJECTIVES,
    )

    # Must match the corrected epsilon diagnostic.
    p.add_argument(
        "--n-centers",
        type=int,
        default=128,
    )
    p.add_argument(
        "--center-selection",
        choices=["random", "top"],
        default="random",
    )
    p.add_argument(
        "--rank-objective",
        default="final_score",
    )
    p.add_argument(
        "--sigmas",
        nargs="+",
        type=float,
        default=[0.01, 0.025, 0.05, 0.10, 0.20],
    )
    p.add_argument(
        "--neighbors-per-sigma",
        type=int,
        default=5,
    )
    p.add_argument(
        "--sample-seed",
        type=int,
        default=0,
    )
    p.add_argument(
        "--ddim-steps",
        type=int,
        default=20,
    )
    p.add_argument(
        "--radius",
        type=float,
        default=None,
    )
    p.add_argument(
        "--project-centers-to-sphere",
        action="store_true",
        default=True,
    )
    p.add_argument(
        "--no-project-centers-to-sphere",
        dest="project_centers_to_sphere",
        action="store_false",
    )
    p.add_argument(
        "--renormalize-neighbors",
        action="store_true",
        default=True,
    )
    p.add_argument(
        "--no-renormalize-neighbors",
        dest="renormalize_neighbors",
        action="store_false",
    )
    p.add_argument(
        "--encode-batch-size",
        type=int,
        default=256,
    )

    # Optional RealNVP comparison.
    p.add_argument(
        "--realnvp-coordinates-csv",
        default="",
        help=(
            "Optional CSV with peptide and post-flow coordinates. "
            "Only peptides common to all representations are retained."
        ),
    )
    p.add_argument(
        "--realnvp-prefix",
        default="",
        help=(
            "Optional explicit post-flow coordinate prefix, e.g. zK_. "
            "Leave empty for auto-detection."
        ),
    )

    # GP validation design.
    p.add_argument(
        "--test-fraction",
        type=float,
        default=0.20,
    )
    p.add_argument(
        "--split-seeds",
        nargs="+",
        type=int,
        default=[11, 22, 33],
    )
    p.add_argument(
        "--train-sizes",
        nargs="+",
        type=int,
        default=[64, 128, 256, 512, 1024],
    )

    p.add_argument(
        "--kernel",
        choices=["matern52", "rbf"],
        default="matern52",
    )
    p.add_argument(
        "--ard",
        action="store_true",
        default=True,
    )
    p.add_argument(
        "--no-ard",
        dest="ard",
        action="store_false",
    )
    p.add_argument(
        "--max-fit-attempts",
        type=int,
        default=2,
    )

    p.add_argument(
        "--device",
        default=(
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        ),
    )
    p.add_argument(
        "--dtype",
        choices=["float32", "float64"],
        default="float64",
        help=(
            "float64 is recommended for GP numerical stability. "
            "Use float32 only if GPU memory is tight."
        ),
    )

    p.add_argument(
        "--save-predictions",
        action="store_true",
        default=True,
    )
    p.add_argument(
        "--no-save-predictions",
        dest="save_predictions",
        action="store_false",
    )

    p.add_argument(
        "--out-dir",
        default=(
            "../../output/"
            "gp_representation_validation_epsilon_vs_h0"
        ),
    )

    return p.parse_args()


if __name__ == "__main__":
    run_benchmark(parse_args())
