# ============================================================
# Phase 1 / pretrain_peptide_direct_sequence_diffusion_bo_ready_h96.py
#
# Replacement for: pretrain_peptide_latent_diffusion_search_cost_sampling_h32_z32.py
#
# Purpose
# -------
# This version removes the GRU-VAE tokenizer entirely. The generative model is a
# direct peptide sequence diffusion model trained to reconstruct length-10
# one-hot peptide tensors from Gaussian-noised versions of themselves.
#
# The architecture intentionally stays compact and comparable to the previous
# GRU-VAE experiments:
#   - sequence length: 10
#   - amino-acid vocabulary: 20
#   - GRU hidden size: 32
#   - GRU layers: 2
#   - time embedding: 32
#
# Later BO coordinate
# -------------------
# The raw diffusion search variable is the initial diffusion base noise epsilon with shape
# [10, 20], flattened to d = 200. For Bayesian optimization, this version also
# fits a lower-dimensional PCA-whitened coordinate from DDIM-inverted training
# epsilon vectors:
#
#     z_bo in R^bo_latent_dim -> inverse PCA -> epsilon -> DDIM -> peptide
#
# The raw epsilon coordinate can still be constrained to the Gaussian typical shell:
#     ||epsilon||_2 = sqrt(10 * 20)
#
# This follows the Search-at-the-Cost-of-Sampling idea: use a deterministic
# generator from a spherical latent/noise coordinate to a discrete design.
#
# Generation path:
#     z_bo -> inverse PCA/whitening -> epsilon -> deterministic DDIM reverse process
#     -> x0_hat -> argmax over amino-acid vocabulary at each position -> peptide
#
# ============================================================

from __future__ import annotations

import argparse
import glob
import json
import math
import os
import random
from dataclasses import asdict, dataclass
from datetime import datetime
from typing import Dict, Iterable, List, Optional, Tuple, Sequence

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, IterableDataset

AA = "ACDEFGHIKLMNPQRSTVWY"
AA_TO_I = {a: i for i, a in enumerate(AA)}
I_TO_AA = {i: a for i, a in enumerate(AA)}
SEQ_LEN = 10
VOCAB = 20


@dataclass
class SequenceDiffusionConfig:
    hidden_size: int = 96
    n_layers: int = 2
    dropout: float = 0.0
    time_dim: int = 32
    train_steps: int = 100
    beta_start: float = 1e-5
    beta_end: float = 8e-3


# ============================================================
# Data utilities
# ============================================================

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def clean_peptide(x: object) -> Optional[str]:
    pep = str(x).strip().upper()
    if len(pep) != SEQ_LEN:
        return None
    if any(ch not in AA_TO_I for ch in pep):
        return None
    return pep


def onehot_encode_peptides(peptides: List[str]) -> torch.Tensor:
    x = torch.zeros((len(peptides), SEQ_LEN, VOCAB), dtype=torch.float32)
    for n, pep in enumerate(peptides):
        pep = str(pep).strip().upper()
        if len(pep) != SEQ_LEN:
            raise ValueError(f"Expected length {SEQ_LEN}, got {len(pep)} for {pep!r}")
        for t, aa in enumerate(pep):
            if aa not in AA_TO_I:
                raise ValueError(f"Unsupported amino acid {aa!r} in {pep!r}")
            x[n, t, AA_TO_I[aa]] = 1.0
    return x


def decode_tensor_to_peptides(x: torch.Tensor) -> List[str]:
    """Decode [B, 10, 20] scores/continuous one-hot estimates by argmax."""
    idx = x.argmax(dim=-1).detach().cpu().tolist()
    return ["".join(I_TO_AA[int(i)] for i in row) for row in idx]


def levenshtein_edit_distance(a: str, b: str) -> int:
    """Edit-distance diagnostic for source peptide -> decoded peptide roundtrips."""
    if a == b:
        return 0
    previous = list(range(len(b) + 1))
    for i, ca in enumerate(a, start=1):
        current = [i]
        for j, cb in enumerate(b, start=1):
            current.append(
                min(
                    current[j - 1] + 1,
                    previous[j] + 1,
                    previous[j - 1] + int(ca != cb),
                )
            )
        previous = current
    return int(previous[-1])


def project_to_radius(x: torch.Tensor, radius: float) -> torch.Tensor:
    return x / x.norm(dim=-1, keepdim=True).clamp_min(1e-8) * float(radius)


class PeptideCSVIterable(IterableDataset):
    """Stream peptide_len10 values from many CSV shards using pandas chunks.

    The corrected chain-mapped all-metal parts contain a `split` column
    generated by deterministic group-level hashing. This iterable can filter
    by split without loading the full dataset into memory.
    """

    def __init__(
        self,
        files: List[str],
        peptide_col: str = "peptide_len10",
        split_col: str = "split",
        split_filter: Optional[str] = None,
        chunksize: int = 8192,
        shuffle_files: bool = True,
        deduplicate_within_epoch: bool = False,
    ):
        self.files = list(files)
        self.peptide_col = peptide_col
        self.split_col = split_col
        self.split_filter = split_filter
        self.chunksize = int(chunksize)
        self.shuffle_files = bool(shuffle_files)
        self.deduplicate_within_epoch = bool(deduplicate_within_epoch)

    def __iter__(self) -> Iterable[torch.Tensor]:
        files = list(self.files)
        if self.shuffle_files:
            random.shuffle(files)

        usecols = [self.peptide_col]
        if self.split_filter is not None:
            usecols.append(self.split_col)

        seen = set()
        for csv_path in files:
            try:
                reader = pd.read_csv(csv_path, usecols=usecols, chunksize=self.chunksize)
            except ValueError as exc:
                raise ValueError(
                    f"Could not read required columns {usecols} from {csv_path}. "
                    "For train/validation/test filtering, make sure the part CSVs contain a split column."
                ) from exc

            for chunk in reader:
                if self.split_filter is not None:
                    mask = chunk[self.split_col].astype(str).str.lower().eq(str(self.split_filter).lower())
                    chunk = chunk.loc[mask]
                    if chunk.empty:
                        continue

                peptides = []
                for value in chunk[self.peptide_col].tolist():
                    pep = clean_peptide(value)
                    if pep is None:
                        continue
                    if self.deduplicate_within_epoch and pep in seen:
                        continue
                    seen.add(pep)
                    peptides.append(pep)
                if peptides:
                    yield onehot_encode_peptides(peptides)


def _resolve_part_path(path_value: object, manifest_dir: str) -> str:
    """Resolve part paths from the manifest, including Windows-style paths."""
    raw = str(path_value).strip().strip('"').strip("'")
    raw = raw.replace("\\", os.sep)
    raw = raw.replace("\\", os.sep)
    if os.path.isabs(raw) and os.path.exists(raw):
        return raw
    if os.path.exists(raw):
        return raw
    candidate = os.path.join(manifest_dir, raw)
    if os.path.exists(candidate):
        return candidate
    candidate2 = os.path.join(manifest_dir, os.path.basename(raw))
    if os.path.exists(candidate2):
        return candidate2
    candidate3 = os.path.join(manifest_dir, "parts", os.path.basename(raw))
    if os.path.exists(candidate3):
        return candidate3
    return raw


def find_pretrain_files(
    parts_dir: str,
    part_glob: str = "metalpdb_ALL_chain_mapped_len10_high_confidence_part_*.csv",
    manifest_csv: Optional[str] = None,
    expected_parts: Optional[int] = None,
) -> List[str]:
    """Find corrected chain-mapped chunked part files.

    Default pattern matches:
    metalpdb_all_metals_chain_mapped_len10_high_confidence_parts/parts/
    metalpdb_ALL_chain_mapped_len10_high_confidence_part_XXXXXX.csv
    """
    if manifest_csv:
        manifest_csv = str(manifest_csv)
        manifest_dir = os.path.dirname(manifest_csv) or "."
        manifest = pd.read_csv(manifest_csv)
        if "window_csv" not in manifest.columns:
            raise ValueError(f"Manifest {manifest_csv} must contain a window_csv column.")
        files = [_resolve_part_path(p, manifest_dir) for p in manifest["window_csv"].tolist()]
    else:
        pattern = os.path.join(parts_dir, part_glob)
        files = sorted(glob.glob(pattern))

    files = [p for p in files if p and os.path.exists(p) and "failures" not in os.path.basename(p)]
    files = sorted(files)

    if not files:
        searched = manifest_csv if manifest_csv else os.path.join(parts_dir, part_glob)
        raise FileNotFoundError(f"No pretraining part files found from: {searched}")

    if expected_parts is not None and int(expected_parts) > 0 and len(files) != int(expected_parts):
        raise ValueError(
            f"Expected {expected_parts} part files, but found {len(files)}. "
            f"First files: {files[:3]} Last files: {files[-3:]}"
        )

    return files


# ============================================================
# Direct sequence diffusion model
# ============================================================

class SinusoidalTimeEmbedding(nn.Module):
    def __init__(self, dim: int):
        super().__init__()
        if dim % 2 != 0:
            raise ValueError("time_dim must be even")
        self.dim = int(dim)

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        half = self.dim // 2
        exponent = -math.log(10000.0) * torch.arange(
            half, device=t.device, dtype=torch.float32
        ) / max(half - 1, 1)
        frequencies = torch.exp(exponent)
        angles = t.float().unsqueeze(-1) * frequencies.unsqueeze(0)
        return torch.cat([torch.sin(angles), torch.cos(angles)], dim=-1)


class DirectSequenceDenoiser(nn.Module):
    """GRU denoiser operating directly on noised one-hot peptide tensors.

    Input:
        x_t: [B, 10, 20] continuous noised one-hot peptide tensor
        t:   [B] diffusion timestep

    Outputs:
        predicted_noise: [B, 10, 20]
        x0_logits:       [B, 10, 20]

    The model has a similar GRU backbone size to the earlier GRU-VAE, but it is
    not a VAE: no encoder posterior, no reparameterization, no KL term, and no
    normalizing flow. Reconstruction is learned by denoising.
    """

    def __init__(self, cfg: SequenceDiffusionConfig):
        super().__init__()
        self.cfg = cfg
        self.x_proj = nn.Linear(VOCAB, cfg.hidden_size)
        self.time_embedding = SinusoidalTimeEmbedding(cfg.time_dim)
        self.time_mlp = nn.Sequential(
            nn.Linear(cfg.time_dim, cfg.hidden_size),
            nn.SiLU(),
            nn.Linear(cfg.hidden_size, cfg.hidden_size),
        )
        self.gru = nn.GRU(
            input_size=cfg.hidden_size,
            hidden_size=cfg.hidden_size,
            num_layers=cfg.n_layers,
            batch_first=True,
            dropout=cfg.dropout if cfg.n_layers > 1 else 0.0,
        )
        self.out_norm = nn.LayerNorm(cfg.hidden_size)
        self.noise_head = nn.Linear(cfg.hidden_size, VOCAB)
        self.x0_logits_head = nn.Linear(cfg.hidden_size, VOCAB)

    def forward(self, x_t: torch.Tensor, t: torch.Tensor) -> Dict[str, torch.Tensor]:
        h = self.x_proj(x_t)
        time_h = self.time_mlp(self.time_embedding(t)).unsqueeze(1)
        h = h + time_h
        h, _ = self.gru(h)
        h = F.silu(self.out_norm(h))
        return {
            "predicted_noise": self.noise_head(h),
            "x0_logits": self.x0_logits_head(h),
        }


class DirectSequenceDiffusion(nn.Module):
    """DDPM epsilon-prediction training + deterministic DDIM sampling.

    This model directly reconstructs peptides in continuous one-hot space. Its
    base noise is the later BO coordinate.
    """

    def __init__(self, cfg: SequenceDiffusionConfig):
        super().__init__()
        self.cfg = cfg
        self.denoiser = DirectSequenceDenoiser(cfg)

        betas = torch.linspace(cfg.beta_start, cfg.beta_end, cfg.train_steps, dtype=torch.float32)
        alphas = 1.0 - betas
        alpha_bars = torch.cumprod(alphas, dim=0)

        self.register_buffer("betas", betas)
        self.register_buffer("alphas", alphas)
        self.register_buffer("alpha_bars", alpha_bars)

    @property
    def bo_dim(self) -> int:
        return SEQ_LEN * VOCAB

    @property
    def bo_radius(self) -> float:
        return math.sqrt(self.bo_dim)

    def q_sample(self, x0: torch.Tensor, t: torch.Tensor, noise: torch.Tensor) -> torch.Tensor:
        alpha_bar_t = self.alpha_bars[t].view(-1, 1, 1)
        return torch.sqrt(alpha_bar_t) * x0 + torch.sqrt(1.0 - alpha_bar_t) * noise

    def training_loss(
        self,
        x0: torch.Tensor,
        recon_ce_weight: float,
        x0_mse_weight: float,
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        batch_size = x0.size(0)
        t = torch.randint(0, self.cfg.train_steps, (batch_size,), device=x0.device)
        noise = torch.randn_like(x0)
        x_t = self.q_sample(x0, t, noise)

        out = self.denoiser(x_t, t)
        predicted_noise = out["predicted_noise"]
        x0_logits = out["x0_logits"]

        eps_mse = F.mse_loss(predicted_noise, noise)
        target = x0.argmax(dim=-1)
        recon_ce = F.cross_entropy(x0_logits.reshape(-1, VOCAB), target.reshape(-1))

        alpha_bar_t = self.alpha_bars[t].view(-1, 1, 1)
        x0_from_eps = (x_t - torch.sqrt(1.0 - alpha_bar_t) * predicted_noise) / torch.sqrt(alpha_bar_t)
        x0_mse = F.mse_loss(x0_from_eps, x0)

        loss = eps_mse + float(recon_ce_weight) * recon_ce + float(x0_mse_weight) * x0_mse

        with torch.no_grad():
            pred = x0_logits.argmax(dim=-1)
            token_acc = (pred == target).float().mean()

        metrics = {
            "loss": float(loss.detach().cpu()),
            "epsilon_mse": float(eps_mse.detach().cpu()),
            "recon_ce": float(recon_ce.detach().cpu()),
            "x0_mse": float(x0_mse.detach().cpu()),
            "token_acc": float(token_acc.detach().cpu()),
        }
        return loss, metrics

    @torch.no_grad()
    def ddim_sample(
        self,
        base_noise: torch.Tensor,
        inference_steps: int = 20,
    ) -> torch.Tensor:
        """Deterministic DDIM sampler from base noise to x0 estimate.

        base_noise can be [B, 10, 20] or flattened [B, 200].
        """
        self.eval()
        if base_noise.ndim == 2:
            x = base_noise.view(-1, SEQ_LEN, VOCAB)
        elif base_noise.ndim == 3:
            x = base_noise
        else:
            raise ValueError(f"Expected base_noise [B,200] or [B,10,20], got {tuple(base_noise.shape)}")

        n_train_steps = self.cfg.train_steps
        inference_steps = min(max(int(inference_steps), 1), n_train_steps)
        timesteps = torch.linspace(n_train_steps - 1, 0, inference_steps, device=x.device).round().long()
        timesteps = torch.unique_consecutive(timesteps)

        for step_index, t_scalar in enumerate(timesteps):
            t = torch.full((x.size(0),), int(t_scalar.item()), device=x.device, dtype=torch.long)
            out = self.denoiser(x, t)
            predicted_noise = out["predicted_noise"]
            alpha_bar_t = self.alpha_bars[t_scalar]

            x0_pred = (x - torch.sqrt(1.0 - alpha_bar_t) * predicted_noise) / torch.sqrt(alpha_bar_t)

            if step_index == len(timesteps) - 1:
                x = x0_pred
                break

            t_prev_scalar = timesteps[step_index + 1]
            alpha_bar_prev = self.alpha_bars[t_prev_scalar]
            x = torch.sqrt(alpha_bar_prev) * x0_pred + torch.sqrt(1.0 - alpha_bar_prev) * predicted_noise

        return x

    @torch.no_grad()
    def ddim_invert(
        self,
        x0: torch.Tensor,
        inference_steps: int = 20,
    ) -> torch.Tensor:
        """Approximate deterministic DDIM inversion from clean one-hot x0 to base noise.

        This supplies a coordinate for existing peptides. The inversion is not exact
        for a learned denoiser, so downstream exports report reconstruction edit
        distance after z_bo -> epsilon -> DDIM -> peptide.
        """
        self.eval()
        if x0.ndim != 3 or x0.shape[1:] != (SEQ_LEN, VOCAB):
            raise ValueError(f"Expected x0 [B,{SEQ_LEN},{VOCAB}], got {tuple(x0.shape)}")

        n_train_steps = self.cfg.train_steps
        inference_steps = min(max(int(inference_steps), 1), n_train_steps)
        timesteps = torch.linspace(0, n_train_steps - 1, inference_steps, device=x0.device).round().long()
        timesteps = torch.unique_consecutive(timesteps)

        x = x0
        for step_index, t_scalar in enumerate(timesteps[:-1]):
            t = torch.full((x.size(0),), int(t_scalar.item()), device=x.device, dtype=torch.long)
            out = self.denoiser(x, t)
            predicted_noise = out["predicted_noise"]
            alpha_bar_t = self.alpha_bars[t_scalar]
            x0_pred = (x - torch.sqrt(1.0 - alpha_bar_t) * predicted_noise) / torch.sqrt(alpha_bar_t)

            t_next_scalar = timesteps[step_index + 1]
            alpha_bar_next = self.alpha_bars[t_next_scalar]
            x = torch.sqrt(alpha_bar_next) * x0_pred + torch.sqrt(1.0 - alpha_bar_next) * predicted_noise

        return x

    @torch.no_grad()
    def decode_base_noise(
        self,
        epsilon: torch.Tensor,
        ddim_steps: int = 20,
    ) -> List[str]:
        x0_hat = self.ddim_sample(epsilon, inference_steps=ddim_steps)
        return decode_tensor_to_peptides(x0_hat)



@torch.no_grad()
def evaluate_split(
    model: DirectSequenceDiffusion,
    loader: DataLoader,
    device: torch.device,
    recon_ce_weight: float,
    x0_mse_weight: float,
    max_batches: int,
) -> Dict[str, float]:
    """Evaluate random-timestep denoising/reconstruction metrics on one split."""
    model.eval()
    sums = {
        "loss": 0.0,
        "epsilon_mse": 0.0,
        "recon_ce": 0.0,
        "x0_mse": 0.0,
        "token_acc": 0.0,
    }
    n_batches = 0

    for x0 in loader:
        x0 = x0.to(device)
        loss, metrics = model.training_loss(
            x0,
            recon_ce_weight=recon_ce_weight,
            x0_mse_weight=x0_mse_weight,
        )
        n_batches += 1
        for key in sums:
            sums[key] += metrics[key]
        if max_batches > 0 and n_batches >= max_batches:
            break

    out = {k: v / max(1, n_batches) for k, v in sums.items()}
    out["n_batches"] = float(n_batches)
    return out


# ============================================================
# Checkpointing / logging
# ============================================================

def append_training_history_csv(path: str, row: Dict[str, float]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    write_header = not os.path.exists(path)
    pd.DataFrame([row]).to_csv(path, mode="a", header=write_header, index=False)


def save_direct_diffusion_checkpoint(
    path: str,
    model: DirectSequenceDiffusion,
    optimizer: torch.optim.Optimizer,
    cfg: SequenceDiffusionConfig,
    args: argparse.Namespace,
    epoch: int,
    metrics: Dict[str, float],
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    payload = {
        "checkpoint_type": "all_metal_direct_peptide_sequence_diffusion_search_cost_sampling",
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "diffusion_config": asdict(cfg),
        "args": vars(args),
        "epoch": int(epoch),
        "metrics": metrics,
        "aa": AA,
        "seq_len": SEQ_LEN,
        "vocab": VOCAB,
        "diffusion_target": "continuous_onehot_peptide_x0",
        "diffusion_prediction": "epsilon_plus_x0_logits",
        "diffusion_sampler": "deterministic_ddim_eta0",
        "bo_coordinate_space": "pca_whitened_ddim_inverted_direct_sequence_diffusion_epsilon",
        "bo_coordinate_shape": [SEQ_LEN, VOCAB],
        "raw_epsilon_dim": int(model.bo_dim),
        "bo_coordinate_dim": int(getattr(args, "bo_latent_dim", model.bo_dim)),
        "recommended_bo_radius": float(model.bo_radius),
        "removed_components": [
            "GRU-VAE posterior encoder",
            "VAE reparameterization",
            "KL term",
            "normalizing flow",
        ],
    }
    torch.save(payload, path)
    with open(path + ".json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "checkpoint_type": payload["checkpoint_type"],
                "diffusion_config": payload["diffusion_config"],
                "epoch": epoch,
                "metrics": metrics,
                "bo_coordinate_space": payload["bo_coordinate_space"],
                "bo_coordinate_shape": payload["bo_coordinate_shape"],
                "bo_coordinate_dim": payload["bo_coordinate_dim"],
                "recommended_bo_radius": payload["recommended_bo_radius"],
            },
            f,
            indent=2,
        )


@torch.no_grad()
def run_generation_sanity_check(
    model: DirectSequenceDiffusion,
    device: torch.device,
    ddim_steps: int,
    n_samples: int,
) -> Dict[str, object]:
    model.eval()
    epsilon = torch.randn(n_samples, model.bo_dim, device=device)
    epsilon = epsilon / epsilon.norm(dim=-1, keepdim=True).clamp(min=1e-8) * model.bo_radius
    x0_hat = model.ddim_sample(epsilon, inference_steps=ddim_steps)
    peptides = decode_tensor_to_peptides(x0_hat)

    counts: Dict[str, int] = {}
    for pep in peptides:
        counts[pep] = counts.get(pep, 0) + 1

    return {
        "n_samples": int(n_samples),
        "unique_fraction": float(len(set(peptides)) / max(len(peptides), 1)),
        "dominant_fraction": float(max(counts.values()) / max(len(peptides), 1)) if counts else float("nan"),
        "base_radius_mean": float(epsilon.norm(dim=-1).mean().item()),
        "raw_epsilon_dim": int(model.bo_dim),
        "bo_coordinate_dim": int(getattr(args, "bo_latent_dim", model.bo_dim)),
        "recommended_bo_radius": float(model.bo_radius),
        "first_20_peptides": peptides[:20],
    }


@torch.no_grad()
def run_reconstruction_sanity_check(
    model: DirectSequenceDiffusion,
    loader: DataLoader,
    device: torch.device,
    n_batches: int,
) -> Dict[str, float]:
    """A simple denoising-reconstruction diagnostic at random timesteps."""
    model.eval()
    sums = {"epsilon_mse": 0.0, "recon_ce": 0.0, "token_acc": 0.0}
    count = 0

    for x0 in loader:
        x0 = x0.to(device)
        batch_size = x0.size(0)
        t = torch.randint(0, model.cfg.train_steps, (batch_size,), device=device)
        noise = torch.randn_like(x0)
        x_t = model.q_sample(x0, t, noise)
        out = model.denoiser(x_t, t)
        predicted_noise = out["predicted_noise"]
        logits = out["x0_logits"]
        target = x0.argmax(dim=-1)
        sums["epsilon_mse"] += float(F.mse_loss(predicted_noise, noise).detach().cpu())
        sums["recon_ce"] += float(F.cross_entropy(logits.reshape(-1, VOCAB), target.reshape(-1)).detach().cpu())
        sums["token_acc"] += float((logits.argmax(dim=-1) == target).float().mean().detach().cpu())
        count += 1
        if count >= n_batches:
            break

    return {k: v / max(count, 1) for k, v in sums.items()}



# ============================================================
# BO coordinate construction from DDIM inversion + PCA whitening
# ============================================================

def iter_peptide_batches(
    files: List[str],
    peptide_col: str,
    split_col: str,
    split_filter: Optional[str],
    chunksize: int,
    deduplicate: bool,
) -> Iterable[Tuple[List[str], torch.Tensor]]:
    """Yield (peptides, onehot) batches for coordinate fitting/export."""
    seen = set()
    usecols = [peptide_col]
    if split_filter is not None:
        usecols.append(split_col)

    for csv_path in files:
        reader = pd.read_csv(csv_path, usecols=usecols, chunksize=chunksize)
        for chunk in reader:
            if split_filter is not None:
                mask = chunk[split_col].astype(str).str.lower().eq(str(split_filter).lower())
                chunk = chunk.loc[mask]
                if chunk.empty:
                    continue

            peptides: List[str] = []
            for value in chunk[peptide_col].tolist():
                pep = clean_peptide(value)
                if pep is None:
                    continue
                if deduplicate and pep in seen:
                    continue
                seen.add(pep)
                peptides.append(pep)

            if peptides:
                yield peptides, onehot_encode_peptides(peptides)


@torch.no_grad()
def collect_inverted_epsilon_matrix(
    model: DirectSequenceDiffusion,
    files: List[str],
    args: argparse.Namespace,
    split_filter: str,
    device: torch.device,
    max_samples: int,
) -> np.ndarray:
    """Collect flattened DDIM-inverted epsilon coordinates for fitting PCA."""
    model.eval()
    rows = []
    n = 0

    for _peptides, x0_cpu in iter_peptide_batches(
        files=files,
        peptide_col=args.peptide_col,
        split_col=args.split_col,
        split_filter=split_filter,
        chunksize=args.chunksize,
        deduplicate=True,
    ):
        x0 = x0_cpu.to(device)
        eps = model.ddim_invert(x0, inference_steps=args.ddim_steps).reshape(x0.size(0), -1)
        if args.project_inverted_epsilon_to_sphere:
            eps = project_to_radius(eps, model.bo_radius)
        rows.append(eps.detach().cpu().numpy().astype(np.float32))
        n += eps.size(0)
        if max_samples > 0 and n >= max_samples:
            break

    if not rows:
        raise RuntimeError(f"No epsilon coordinates collected for split={split_filter!r}")

    mat = np.concatenate(rows, axis=0)
    if max_samples > 0 and mat.shape[0] > max_samples:
        mat = mat[:max_samples]
    return mat


def fit_pca_whitener(x: np.ndarray, bo_latent_dim: int, eps: float = 1e-6) -> Dict[str, np.ndarray]:
    """Fit PCA/whitening on training epsilon only."""
    if x.ndim != 2:
        raise ValueError(f"Expected 2D matrix, got {x.shape}")
    n, d = x.shape
    k = min(int(bo_latent_dim), d, max(1, n - 1))
    mean = x.mean(axis=0, keepdims=True)
    xc = x - mean

    # Compact SVD. Components are rows [k, d].
    _, s, vt = np.linalg.svd(xc, full_matrices=False)
    components = vt[:k].astype(np.float32)
    scores = xc @ components.T
    score_std = scores.std(axis=0, keepdims=True).astype(np.float32)
    score_std = np.maximum(score_std, eps)

    explained = (s ** 2) / max(1, n - 1)
    total = float(explained.sum()) if explained.size else 0.0
    evr = explained[:k] / max(total, eps)

    return {
        "mean": mean.astype(np.float32),
        "components": components,
        "score_std": score_std,
        "explained_variance_ratio": evr.astype(np.float32),
    }


def pca_project(epsilon_flat: np.ndarray, pca: Dict[str, np.ndarray]) -> np.ndarray:
    return ((epsilon_flat - pca["mean"]) @ pca["components"].T) / pca["score_std"]


def pca_inverse(z_bo: np.ndarray, pca: Dict[str, np.ndarray]) -> np.ndarray:
    return (z_bo * pca["score_std"]) @ pca["components"] + pca["mean"]


def geometry_diagnostics_np(x: np.ndarray, eps: float = 1e-8) -> Dict[str, float]:
    if x.ndim != 2 or x.shape[0] < 2:
        return {
            "effective_dim_pr": float("nan"),
            "pc1_variance_fraction": float("nan"),
            "pcs90": float("nan"),
            "pcs95": float("nan"),
            "mean_abs_offdiag_corr": float("nan"),
            "max_abs_offdiag_corr": float("nan"),
        }
    xc = x.astype(np.float64) - x.astype(np.float64).mean(axis=0, keepdims=True)
    cov = (xc.T @ xc) / max(1, x.shape[0] - 1)
    eig = np.linalg.eigvalsh(cov).clip(min=0.0)
    total = max(float(eig.sum()), eps)
    pr = total * total / max(float((eig ** 2).sum()), eps)
    eig_desc = eig[::-1]
    frac = eig_desc / total
    cum = np.cumsum(frac)

    z = xc / np.maximum(xc.std(axis=0, keepdims=True), eps)
    corr = (z.T @ z) / float(z.shape[0])
    off = corr - np.diag(np.diag(corr))
    denom = max(1, z.shape[1] * (z.shape[1] - 1))

    return {
        "effective_dim_pr": float(pr),
        "pc1_variance_fraction": float(frac[0]),
        "pcs90": float(np.searchsorted(cum, 0.90) + 1),
        "pcs95": float(np.searchsorted(cum, 0.95) + 1),
        "mean_abs_offdiag_corr": float(np.abs(off).sum() / denom),
        "max_abs_offdiag_corr": float(np.abs(off).max()),
    }


@torch.no_grad()
def build_and_export_bo_coordinates(
    model: DirectSequenceDiffusion,
    files: List[str],
    args: argparse.Namespace,
    device: torch.device,
    checkpoint_label: str,
) -> Dict[str, object]:
    """Fit train-only PCA-whitened BO coordinates and export split-labeled CSV."""
    if not args.export_bo_coordinates:
        return {}

    print("[BO-EXPORT] Collecting training DDIM-inverted epsilon for PCA/whitening...")
    train_eps = collect_inverted_epsilon_matrix(
        model=model,
        files=files,
        args=args,
        split_filter=args.train_split,
        device=device,
        max_samples=args.bo_pca_fit_max_samples,
    )
    pca = fit_pca_whitener(train_eps, args.bo_latent_dim)

    pca_path = os.path.join(args.out_dir, "direct_diffusion_bo_pca_whitener.npz")
    np.savez(
        pca_path,
        mean=pca["mean"],
        components=pca["components"],
        score_std=pca["score_std"],
        explained_variance_ratio=pca["explained_variance_ratio"],
    )

    explained_cum = float(pca["explained_variance_ratio"].sum())
    train_z = pca_project(train_eps, pca)
    geom = geometry_diagnostics_np(train_z)

    out_csv = os.path.join(args.out_dir, "direct_diffusion_pca_bo_coordinates.csv")
    rows: List[Dict[str, object]] = []
    total = 0

    for split_name in [args.train_split, args.validation_split, args.test_split]:
        split_written = 0
        split_cap = int(args.bo_export_max_per_split)
        for peptides, x0_cpu in iter_peptide_batches(
            files=files,
            peptide_col=args.peptide_col,
            split_col=args.split_col,
            split_filter=split_name,
            chunksize=args.chunksize,
            deduplicate=True,
        ):
            x0 = x0_cpu.to(device)
            eps = model.ddim_invert(x0, inference_steps=args.ddim_steps).reshape(x0.size(0), -1)
            if args.project_inverted_epsilon_to_sphere:
                eps = project_to_radius(eps, model.bo_radius)

            eps_np = eps.detach().cpu().numpy().astype(np.float32)
            z_bo = pca_project(eps_np, pca).astype(np.float32)
            eps_back_np = pca_inverse(z_bo, pca).astype(np.float32)
            eps_back = torch.tensor(eps_back_np, dtype=torch.float32, device=device)
            if args.project_generated_epsilon_to_sphere:
                eps_back = project_to_radius(eps_back, model.bo_radius)

            x0_back = model.ddim_sample(eps_back, inference_steps=args.ddim_steps)
            decoded = decode_tensor_to_peptides(x0_back)
            source = peptides

            x_l2 = torch.linalg.norm(
                x0.reshape(x0.size(0), -1) - x0_back.reshape(x0.size(0), -1),
                dim=-1,
            ).detach().cpu().numpy()

            for i, pep in enumerate(source):
                if split_cap > 0 and split_written >= split_cap:
                    break
                row: Dict[str, object] = {
                    "peptide": pep,
                    "peptide_len10": pep,
                    "split": split_name,
                    "decoded_from_bo_latent": decoded[i],
                    "source_to_decoded_edit": levenshtein_edit_distance(pep, decoded[i]),
                    "ddim_x0_l2": float(x_l2[i]),
                    "epsilon_norm": float(np.linalg.norm(eps_np[i])),
                    "bo_latent_norm": float(np.linalg.norm(z_bo[i])),
                }
                for j in range(z_bo.shape[1]):
                    row[f"z_bo_{j:02d}"] = float(z_bo[i, j])
                if args.export_raw_epsilon_columns:
                    for j in range(eps_np.shape[1]):
                        row[f"epsilon_{j:03d}"] = float(eps_np[i, j])
                rows.append(row)
                split_written += 1
                total += 1

            if split_cap > 0 and split_written >= split_cap:
                break

    pd.DataFrame(rows).to_csv(out_csv, index=False)

    meta = {
        "checkpoint_label": checkpoint_label,
        "bo_coordinate_space": "pca_whitened_ddim_inverted_direct_sequence_diffusion_epsilon",
        "raw_epsilon_dim": int(model.bo_dim),
        "bo_latent_dim": int(pca["components"].shape[0]),
        "bo_pca_fit_split": args.train_split,
        "bo_pca_fit_n": int(train_eps.shape[0]),
        "bo_pca_explained_variance_fraction": explained_cum,
        "project_inverted_epsilon_to_sphere": bool(args.project_inverted_epsilon_to_sphere),
        "project_generated_epsilon_to_sphere": bool(args.project_generated_epsilon_to_sphere),
        "pca_path": pca_path,
        "coordinate_csv": out_csv,
        "n_exported_rows": int(total),
        "train_z_geometry": geom,
    }
    with open(os.path.join(args.out_dir, "direct_diffusion_bo_coordinate_export.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)
    print("[BO-EXPORT] Saved:", out_csv)
    print("[BO-EXPORT] Metadata:", meta)
    return meta



# ============================================================
# Training
# ============================================================

def make_split_loader(
    files: List[str],
    args: argparse.Namespace,
    split_filter: Optional[str],
    shuffle_files: bool,
) -> DataLoader:
    dataset = PeptideCSVIterable(
        files,
        peptide_col=args.peptide_col,
        split_col=args.split_col,
        split_filter=split_filter,
        chunksize=args.chunksize,
        shuffle_files=shuffle_files,
        deduplicate_within_epoch=args.deduplicate,
    )
    return DataLoader(dataset, batch_size=None, num_workers=0)


def train(args: argparse.Namespace) -> str:
    set_seed(args.seed)
    device = torch.device(args.device)

    cfg = SequenceDiffusionConfig(
        hidden_size=args.hidden_size,
        n_layers=args.n_layers,
        dropout=args.dropout,
        time_dim=args.time_dim,
        train_steps=args.diffusion_train_steps,
        beta_start=args.diffusion_beta_start,
        beta_end=args.diffusion_beta_end,
    )

    files = find_pretrain_files(
        parts_dir=args.parts_dir,
        part_glob=args.part_glob,
        manifest_csv=args.manifest_csv,
        expected_parts=args.expected_parts,
    )

    train_loader = make_split_loader(files, args, args.train_split, shuffle_files=True)
    val_loader = make_split_loader(files, args, args.validation_split, shuffle_files=False)
    test_loader = make_split_loader(files, args, args.test_split, shuffle_files=False)

    os.makedirs(args.out_dir, exist_ok=True)
    history_path = os.path.join(args.out_dir, "pretraining_history_direct_sequence_diffusion.csv")
    checkpoint_path = os.path.join(args.out_dir, f"pretrained_direct_sequence_diffusion_bo_ready_h{cfg.hidden_size}.pt")
    best_val_path = os.path.join(args.out_dir, f"best_validation_direct_sequence_diffusion_bo_ready_h{cfg.hidden_size}.pt")
    final_test_json_path = os.path.join(args.out_dir, "final_test_metrics_direct_sequence_diffusion.json")

    if args.no_resume and os.path.exists(history_path) and not args.append_history:
        os.remove(history_path)

    model = DirectSequenceDiffusion(cfg).to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.diffusion_lr,
        weight_decay=args.weight_decay,
    )

    print("DEVICE:", device)
    print("Corrected chain-mapped CSV shards:", len(files))
    print("First part:", files[0])
    print("Last part:", files[-1])
    print("Split column:", args.split_col)
    print("Train/validation/test split names:", args.train_split, args.validation_split, args.test_split)
    print("Direct sequence diffusion config:", asdict(cfg))
    print("BO coordinate shape:", [SEQ_LEN, VOCAB])
    print("BO coordinate dimension:", model.bo_dim)
    print("Recommended BO radius:", model.bo_radius)
    print("No GRU-VAE, no KL, no encoder posterior, no normalizing flow.")
    print("BO latent coordinate:", f"PCA-whitened DDIM epsilon, dim={args.bo_latent_dim}, raw_dim={model.bo_dim}")

    best_val_loss = float("inf")
    best_val_epoch = -1

    for epoch in range(1, args.diffusion_epochs + 1):
        model.train()
        sums = {
            "loss": 0.0,
            "epsilon_mse": 0.0,
            "recon_ce": 0.0,
            "x0_mse": 0.0,
            "token_acc": 0.0,
        }
        n_batches = 0

        for x0 in train_loader:
            x0 = x0.to(device)
            optimizer.zero_grad(set_to_none=True)
            loss, metrics = model.training_loss(
                x0,
                recon_ce_weight=args.recon_ce_weight,
                x0_mse_weight=args.x0_mse_weight,
            )
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()

            n_batches += 1
            for key in sums:
                sums[key] += metrics[key]

            if args.log_every and n_batches % args.log_every == 0:
                avg = {k: v / n_batches for k, v in sums.items()}
                print(
                    f"[DIRECT-DIFF][train] epoch={epoch} batch={n_batches} "
                    f"loss={avg['loss']:.4f} eps_mse={avg['epsilon_mse']:.4f} "
                    f"ce={avg['recon_ce']:.4f} x0_mse={avg['x0_mse']:.4f} "
                    f"acc={avg['token_acc']:.4f}"
                )

        train_metrics = {k: v / max(1, n_batches) for k, v in sums.items()}
        train_metrics["n_batches"] = float(n_batches)

        val_metrics = evaluate_split(
            model=model,
            loader=val_loader,
            device=device,
            recon_ce_weight=args.recon_ce_weight,
            x0_mse_weight=args.x0_mse_weight,
            max_batches=args.validation_batches,
        )

        row: Dict[str, float] = {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "stage": "direct_sequence_diffusion_chain_mapped_parts",
            "epoch": epoch,
            "diffusion_lr": optimizer.param_groups[0]["lr"],
            "train_steps": cfg.train_steps,
            "hidden_size": cfg.hidden_size,
            "n_layers": cfg.n_layers,
            "time_dim": cfg.time_dim,
            "bo_coordinate_dim": model.bo_dim,
            "bo_radius": model.bo_radius,
            "n_part_files": float(len(files)),
        }
        for k, v in train_metrics.items():
            row[f"train_{k}"] = v
        for k, v in val_metrics.items():
            row[f"validation_{k}"] = v

        append_training_history_csv(history_path, row)

        # Save last epoch checkpoint every epoch.
        save_direct_diffusion_checkpoint(
            checkpoint_path,
            model=model,
            optimizer=optimizer,
            cfg=cfg,
            args=args,
            epoch=epoch,
            metrics={
                **{f"train_{k}": v for k, v in train_metrics.items()},
                **{f"validation_{k}": v for k, v in val_metrics.items()},
            },
        )

        # Save best validation checkpoint.
        if val_metrics["loss"] <= best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_val_epoch = epoch
            save_direct_diffusion_checkpoint(
                best_val_path,
                model=model,
                optimizer=optimizer,
                cfg=cfg,
                args=args,
                epoch=epoch,
                metrics={
                    **{f"train_{k}": v for k, v in train_metrics.items()},
                    **{f"validation_{k}": v for k, v in val_metrics.items()},
                    "checkpoint_selection": "minimum_validation_loss",
                },
            )

        print(f"[DIRECT-DIFF] epoch={epoch} train={train_metrics} validation={val_metrics}")
        print(f"[DIRECT-DIFF] best_validation_loss={best_val_loss:.6f} at epoch={best_val_epoch}")

    # Final test evaluation is run once after training to avoid repeatedly scanning all test shards.
    test_metrics = evaluate_split(
        model=model,
        loader=test_loader,
        device=device,
        recon_ce_weight=args.recon_ce_weight,
        x0_mse_weight=args.x0_mse_weight,
        max_batches=args.test_batches,
    )
    with open(final_test_json_path, "w", encoding="utf-8") as f:
        json.dump(test_metrics, f, indent=2)

    sanity_metrics = run_generation_sanity_check(
        model=model,
        device=device,
        ddim_steps=args.ddim_steps,
        n_samples=args.sanity_samples,
    )
    sanity_path = os.path.join(args.out_dir, "direct_sequence_diffusion_generation_sanity.json")
    with open(sanity_path, "w", encoding="utf-8") as f:
        json.dump(sanity_metrics, f, indent=2)

    # Reconstruction sanity on validation split, because it is not used for optimizer steps.
    recon_loader = make_split_loader(files, args, args.validation_split, shuffle_files=False)
    recon_metrics = run_reconstruction_sanity_check(
        model=model,
        loader=recon_loader,
        device=device,
        n_batches=args.reconstruction_sanity_batches,
    )
    recon_path = os.path.join(args.out_dir, "direct_sequence_diffusion_reconstruction_sanity_validation.json")
    with open(recon_path, "w", encoding="utf-8") as f:
        json.dump(recon_metrics, f, indent=2)

    bo_export_metrics = build_and_export_bo_coordinates(
        model=model,
        files=files,
        args=args,
        device=device,
        checkpoint_label=f"epoch_{args.diffusion_epochs}",
    )

    print("Saved last checkpoint:", checkpoint_path)
    print("Saved best validation checkpoint:", best_val_path)
    print("Saved training history:", history_path)
    print("Saved final test metrics:", final_test_json_path)
    print("Saved generation sanity:", sanity_path)
    print("Saved validation reconstruction sanity:", recon_path)
    print("Final test metrics:", test_metrics)
    print("Generation sanity:", sanity_metrics)
    print("Validation reconstruction sanity:", recon_metrics)

    return checkpoint_path


# ============================================================
# CLI
# ============================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Direct length-10 peptide sequence diffusion pretraining. "
            "This removes the GRU-VAE tokenizer and trains a GRU-based denoising "
            "diffusion model directly on continuous one-hot peptide tensors."
        )
    )

    p.add_argument("--parts-dir", default=r"metalpdb_all_metals_chain_mapped_len10_high_confidence_parts\parts")
    p.add_argument("--part-glob", default="metalpdb_ALL_chain_mapped_len10_high_confidence_part_*.csv")
    p.add_argument("--manifest-csv", default=None, help="Optional manifest CSV with a window_csv column. Overrides --parts-dir/--part-glob discovery.")
    p.add_argument("--expected-parts", type=int, default=73, help="Expected number of chunked part files. Set 0 to disable this check.")
    p.add_argument("--peptide-col", default="peptide_len10")
    p.add_argument("--split-col", default="split")
    p.add_argument("--train-split", default="train")
    p.add_argument("--validation-split", default="validation")
    p.add_argument("--test-split", default="test")
    p.add_argument("--out-dir", default="transfer_peptide_direct_sequence_diffusion_bo_ready_h96")

    # Architecture: similar scale to previous GRU-VAE backbone.
    p.add_argument("--hidden-size", type=int, default=96)
    p.add_argument("--n-layers", type=int, default=2)
    p.add_argument("--dropout", type=float, default=0.0)
    p.add_argument("--time-dim", type=int, default=32)

    # Diffusion.
    p.add_argument("--diffusion-epochs", type=int, default=250)
    p.add_argument("--diffusion-lr", type=float, default=3e-4)
    p.add_argument("--diffusion-train-steps", type=int, default=100)
    p.add_argument("--diffusion-beta-start", type=float, default=1e-5)
    p.add_argument("--diffusion-beta-end", type=float, default=8e-3)
    p.add_argument("--ddim-steps", type=int, default=50)

    # Loss weights.
    p.add_argument("--recon-ce-weight", type=float, default=0.5)
    p.add_argument("--x0-mse-weight", type=float, default=0.1)

    # Data / optimization.
    p.add_argument("--chunksize", type=int, default=8192)
    p.add_argument("--validation-batches", type=int, default=50, help="Maximum validation chunks/batches per epoch; set 0 for full validation scan.")
    p.add_argument("--test-batches", type=int, default=0, help="Maximum test chunks/batches after training; set 0 for full test scan.")
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--grad-clip", type=float, default=5.0)
    p.add_argument("--deduplicate", action="store_true")
    p.add_argument("--log-every", type=int, default=10)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")

    # BO coordinate export from DDIM inversion.
    p.add_argument("--export-bo-coordinates", action=argparse.BooleanOptionalAction, default=True)
    p.add_argument("--bo-latent-dim", type=int, default=64,
                   help="PCA-whitened BO coordinate dimension fitted on train inverted epsilon.")
    p.add_argument("--bo-pca-fit-max-samples", type=int, default=50000,
                   help="Maximum train peptides used to fit PCA/whitener. 0 means all.")
    p.add_argument("--bo-export-max-per-split", type=int, default=0,
                   help="Maximum rows exported per split. 0 means all; use a cap for quick diagnostics.")
    p.add_argument("--project-inverted-epsilon-to-sphere", action=argparse.BooleanOptionalAction, default=False,
                   help="Project DDIM-inverted epsilon to the typical sphere before PCA fitting/export.")
    p.add_argument("--project-generated-epsilon-to-sphere", action=argparse.BooleanOptionalAction, default=False,
                   help="Project inverse-PCA generated epsilon to the typical sphere before DDIM sampling.")
    p.add_argument("--export-raw-epsilon-columns", action="store_true",
                   help="Also export all 200 raw epsilon columns. Off by default to keep CSV compact.")

    # Output behavior.
    p.add_argument("--no-resume", action="store_true")
    p.add_argument("--append-history", action="store_true")
    p.add_argument("--sanity-samples", type=int, default=512)
    p.add_argument("--reconstruction-sanity-batches", type=int, default=10)

    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    train(args)
