"""
Extract length-10 peptide windows centered on metal-binding residues from
MetalPDB CSV files generated by find_all_metalpdb_unique_proteins.py.

Default input folder
--------------------
metalpdb_all_metals_unique/
    metalpdb_all_metals_all_records.csv
    metalpdb_unique_protein_metal_pairs.csv
    metalpdb_unique_proteins_deduplicated.csv
    metalpdb_summary_by_metal_after_dedup.csv
    metalpdb_failed_metals.csv
    raw_json/

Main output files
-----------------
parts/metalpdb_binding_windows_len10_part_000001.csv, ...
    Chunked output files. A new CSV is started every --save-every-k input rows.

parts/metalpdb_binding_windows_len10_failures_part_000001.csv, ...
    Chunked failure logs.

metalpdb_binding_windows_len10_manifest.csv
    List of generated chunk files and row counts.

Optional final files, created only with --make-final-files:
    metalpdb_binding_windows_len10_all_metals.csv
    metalpdb_binding_windows_len10_all_metals_deduplicated.csv
    metalpdb_binding_windows_len10_unique_peptide_metal.csv
    metalpdb_binding_windows_len10_summary_by_metal.csv

Notes
-----
- The script downloads mmCIF files from RCSB and caches them locally.
- For even window length 10, the binding residue is placed at index 4:
  labels = 0 0 0 0 1 0 0 0 0 0
  This gives 4 residues on the left and 5 residues on the right.
- Rows close to chain termini are skipped by default. Set --pad-termini to pad
  with X instead of skipping.
"""

from __future__ import annotations

import argparse
import ast
import json
import math
import re
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import pandas as pd
import requests
from Bio.PDB import MMCIFParser
from Bio.PDB.Polypeptide import is_aa
from Bio.SeqUtils import seq1


RCSB_CIF_URL = "https://files.rcsb.org/download/{pdb}.cif"
STANDARD_AA = set("ACDEFGHIKLMNPQRSTVWY")
DEFAULT_INPUT_DIR = Path("metalpdb_all_metals_unique")
DEFAULT_INPUT_CSV = DEFAULT_INPUT_DIR / "metalpdb_all_metals_all_records.csv"
DEFAULT_OUTPUT_DIR = DEFAULT_INPUT_DIR / "binding_windows_len10"


# ---------------------------------------------------------------------
# General parsing helpers
# ---------------------------------------------------------------------
def first_existing_column(df: pd.DataFrame, candidates: Sequence[str]) -> Optional[str]:
    """Return the first column name that exists in df."""
    for c in candidates:
        if c in df.columns:
            return c
    lower_map = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower_map:
            return lower_map[c.lower()]
    return None


def is_missing(x: Any) -> bool:
    if x is None:
        return True
    try:
        if isinstance(x, float) and math.isnan(x):
            return True
    except Exception:
        pass
    s = str(x).strip()
    return s == "" or s.lower() in {"nan", "none", "null"}


def parse_possible_literal(value: Any) -> Any:
    """Parse JSON/Python-literal strings safely; otherwise return original value."""
    if is_missing(value):
        return None
    if isinstance(value, (list, dict)):
        return value
    if not isinstance(value, str):
        return value

    text = value.strip()
    if not text:
        return None

    # Try JSON first, then Python literal strings produced by pandas CSV round-trips.
    for parser in (json.loads, ast.literal_eval):
        try:
            return parser(text)
        except Exception:
            continue
    return value


def safe_three_to_one(resname: str) -> str:
    """Convert 3-letter residue name to one-letter amino acid code."""
    if is_missing(resname):
        return "X"
    resname = str(resname).strip().upper()
    try:
        aa = seq1(resname, custom_map={})
    except Exception:
        return "X"
    aa = str(aa).strip().upper()
    if len(aa) != 1 or aa not in STANDARD_AA:
        return "X"
    return aa


def clean_pdb_id(value: Any) -> Optional[str]:
    if is_missing(value):
        return None
    s = str(value).strip().lower()
    # common cases: 1abc, 1ABC, ['1abc'] accidentally stringified, etc.
    m = re.search(r"[0-9][a-zA-Z0-9]{3}", s)
    return m.group(0).lower() if m else None


def clean_metal_symbol(value: Any) -> Optional[str]:
    if is_missing(value):
        return None
    v = parse_possible_literal(value)
    if isinstance(v, list) and v:
        v = v[0]
    if isinstance(v, dict):
        for k in ["metal", "symbol", "element", "name"]:
            if k in v and not is_missing(v[k]):
                v = v[k]
                break
    s = str(v).strip()
    m = re.search(r"[A-Za-z]{1,2}", s)
    return m.group(0).title() if m else None


def normalize_chain_id(chain: Any) -> Optional[str]:
    if is_missing(chain):
        return None
    chain = str(chain).strip()
    return chain if chain else None


def normalize_resseq(resnum: Any) -> Optional[int]:
    """Convert residue number to int. Handles strings like '123', '123A', '-1'."""
    if is_missing(resnum):
        return None
    text = str(resnum).strip()
    m = re.search(r"-?\d+", text)
    if not m:
        return None
    try:
        return int(m.group(0))
    except Exception:
        return None


# ---------------------------------------------------------------------
# Ligand extraction from MetalPDB rows
# ---------------------------------------------------------------------
def ligands_from_nested_metals(row: pd.Series) -> List[Dict[str, Any]]:
    """Parse old-style 'metals' column: list of metal records with ligands."""
    if "metals" not in row.index or is_missing(row.get("metals")):
        return []

    metals_obj = parse_possible_literal(row.get("metals"))
    if isinstance(metals_obj, dict):
        metals_obj = [metals_obj]
    if not isinstance(metals_obj, list):
        return []

    out: List[Dict[str, Any]] = []
    for metal_rec in metals_obj:
        if not isinstance(metal_rec, dict):
            continue
        ligs = metal_rec.get("ligands", [])
        if isinstance(ligs, dict):
            ligs = [ligs]
        if not isinstance(ligs, list):
            continue
        for lig in ligs:
            if isinstance(lig, dict):
                lig2 = dict(lig)
                if "metal" not in lig2:
                    lig2["metal"] = metal_rec.get("metal") or metal_rec.get("symbol")
                out.append(lig2)
    return out


def ligands_from_ligands_column(row: pd.Series) -> List[Dict[str, Any]]:
    """Parse current API 'ligands' column if it is a list/dict string."""
    if "ligands" not in row.index or is_missing(row.get("ligands")):
        return []

    lig_obj = parse_possible_literal(row.get("ligands"))
    if isinstance(lig_obj, dict):
        return [lig_obj]
    if isinstance(lig_obj, list):
        return [x for x in lig_obj if isinstance(x, dict)]
    return []


def ligands_from_flattened_columns(row: pd.Series) -> List[Dict[str, Any]]:
    """
    Parse columns like ligands.0.chain, ligands.0.residue_pdb_number, etc.
    created by pd.json_normalize.
    """
    pattern = re.compile(r"^ligands\.(\d+)\.(.+)$")
    grouped: Dict[int, Dict[str, Any]] = defaultdict(dict)
    for col, val in row.items():
        m = pattern.match(str(col))
        if not m:
            continue
        idx = int(m.group(1))
        key = m.group(2)
        grouped[idx][key] = val
    return [grouped[i] for i in sorted(grouped)]


def extract_ligands(row: pd.Series) -> List[Dict[str, Any]]:
    """Return all ligand dicts found in a MetalPDB CSV row."""
    ligands: List[Dict[str, Any]] = []
    ligands.extend(ligands_from_nested_metals(row))
    ligands.extend(ligands_from_ligands_column(row))
    ligands.extend(ligands_from_flattened_columns(row))
    return ligands


def ligand_to_binding_residue(lig: Dict[str, Any], fallback_metal: Optional[str]) -> Optional[Tuple[str, int, str, Optional[str]]]:
    """
    Convert a ligand dictionary to (chain_id, residue_number, residue_name, metal_symbol).
    Keeps only standard amino-acid ligands.
    """
    chain = None
    for key in ["chain", "chain_id", "auth_asym_id", "label_asym_id", "asym_id"]:
        if key in lig and not is_missing(lig[key]):
            chain = normalize_chain_id(lig[key])
            break

    resnum = None
    for key in ["residue_pdb_number", "auth_seq_id", "residue_number", "resseq", "resnum", "residue_num"]:
        if key in lig and not is_missing(lig[key]):
            resnum = normalize_resseq(lig[key])
            break

    resname = None
    for key in ["residue", "resname", "res_name", "comp_id", "residue_name", "ligand"]:
        if key in lig and not is_missing(lig[key]):
            resname = str(lig[key]).strip().upper()
            break

    if chain is None or resnum is None or resname is None:
        return None

    aa1 = safe_three_to_one(resname)
    if aa1 == "X":
        return None

    metal = None
    for key in ["metal", "metal_symbol", "element", "metal_name"]:
        if key in lig and not is_missing(lig[key]):
            metal = clean_metal_symbol(lig[key])
            break
    if metal is None:
        metal = fallback_metal

    return chain, resnum, resname, metal


def extract_binding_residues_from_row(row: pd.Series, metal_col: Optional[str]) -> Dict[Tuple[str, str], set]:
    """
    Return {(metal_symbol, chain_id): set(residue_numbers)} for one MetalPDB row.
    """
    fallback_metal = clean_metal_symbol(row.get(metal_col)) if metal_col else None
    out: Dict[Tuple[str, str], set] = defaultdict(set)

    for lig in extract_ligands(row):
        parsed = ligand_to_binding_residue(lig, fallback_metal=fallback_metal)
        if parsed is None:
            continue
        chain, resnum, _resname, metal = parsed
        if metal is None:
            metal = fallback_metal or "UNKNOWN"
        out[(metal, chain)].add(resnum)

    return out


# ---------------------------------------------------------------------
# Structure and peptide-window helpers
# ---------------------------------------------------------------------
def download_cif(pdb_id: str, cif_cache_dir: Path, timeout_sec: float = 60.0, max_retries: int = 3) -> Path:
    pdb_id = pdb_id.lower()
    cif_cache_dir.mkdir(parents=True, exist_ok=True)
    out_path = cif_cache_dir / f"{pdb_id}.cif"
    if out_path.exists() and out_path.stat().st_size > 0:
        return out_path

    url = RCSB_CIF_URL.format(pdb=pdb_id)
    last_err = None
    for attempt in range(1, max_retries + 1):
        try:
            r = requests.get(url, timeout=timeout_sec)
            r.raise_for_status()
            out_path.write_bytes(r.content)
            return out_path
        except Exception as e:
            last_err = e
            if attempt < max_retries:
                time.sleep(0.5 * attempt)
    raise RuntimeError(f"Could not download CIF for {pdb_id}: {last_err}")


def load_structure(cif_path: Path):
    parser = MMCIFParser(QUIET=True)
    return parser.get_structure(cif_path.stem, str(cif_path))


def chain_sequence_and_resseqs_from_structure(structure: Any, chain_id: str) -> Tuple[str, List[int], List[str]]:
    """
    Build sequence and aligned author residue numbers for one chain.
    Returns sequence, residue_numbers, residue_names.
    """
    model = next(structure.get_models())
    if chain_id not in model:
        raise KeyError(f"Chain {chain_id} not found")

    chain = model[chain_id]
    seq_chars: List[str] = []
    resseqs: List[int] = []
    resnames: List[str] = []

    for res in chain:
        if not is_aa(res, standard=True):
            continue
        resname = res.get_resname().upper()
        aa1 = safe_three_to_one(resname)
        if aa1 == "X":
            continue
        seq_chars.append(aa1)
        resseqs.append(int(res.get_id()[1]))
        resnames.append(resname)

    return "".join(seq_chars), resseqs, resnames


def centered_window(sequence: str, center_idx: int, window_len: int, pad_termini: bool = False):
    """
    Return peptide window centered on center_idx.
    For window_len=10, binding residue is at index 4 by default.
    """
    if window_len <= 0:
        raise ValueError("window_len must be positive")

    left = window_len // 2 - 1 if window_len % 2 == 0 else window_len // 2
    right = window_len - 1 - left
    start = center_idx - left
    end = center_idx + right + 1

    if not pad_termini:
        if start < 0 or end > len(sequence):
            return None
        pep = sequence[start:end]
        center_pos = center_idx - start
        return pep, start, end, center_pos

    # Pad with X if window exceeds termini.
    raw_chars: List[str] = []
    for idx in range(start, end):
        if 0 <= idx < len(sequence):
            raw_chars.append(sequence[idx])
        else:
            raw_chars.append("X")
    pep = "".join(raw_chars)
    center_pos = center_idx - start
    return pep, start, end, center_pos


def label_string(window_len: int, center_pos: int) -> str:
    labels = [0] * window_len
    labels[center_pos] = 1
    return " ".join(map(str, labels))



# ---------------------------------------------------------------------
# Chunked-output helpers
# ---------------------------------------------------------------------
def write_chunk_csv(
    rows: List[Dict[str, Any]],
    out_path: Path,
    columns: Optional[Sequence[str]] = None,
) -> int:
    """Write one chunk CSV and clear no external state. Returns rows written."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        pd.DataFrame(columns=list(columns) if columns else None).to_csv(out_path, index=False)
        return 0
    df = pd.DataFrame(rows)
    if columns is not None:
        for col in columns:
            if col not in df.columns:
                df[col] = None
        df = df[list(columns)]
    df.to_csv(out_path, index=False)
    return len(df)


def iter_csv_files(files: Sequence[Path], chunksize: int = 100_000):
    """Yield dataframe chunks from a list of CSV files."""
    for path in files:
        if not path.exists() or path.stat().st_size == 0:
            continue
        try:
            for chunk in pd.read_csv(path, chunksize=chunksize):
                yield chunk
        except pd.errors.EmptyDataError:
            continue


def build_final_outputs_from_parts(
    window_part_files: Sequence[Path],
    failure_part_files: Sequence[Path],
    output_dir: Path,
    window_len: int,
    combine_chunksize: int = 100_000,
) -> None:
    """
    Build the same final CSVs as the original script from chunk files.

    This still stores deduplication keys in memory, but it avoids holding all raw
    rows in memory during extraction. If your dataset is extremely large, run
    without --make-final-files and deduplicate later with a database/Dask/Polars.
    """
    peptide_col = f"peptide_len{window_len}"
    all_csv = output_dir / f"metalpdb_binding_windows_len{window_len}_all_metals.csv"
    dedup_csv = output_dir / f"metalpdb_binding_windows_len{window_len}_all_metals_deduplicated.csv"
    peptide_metal_csv = output_dir / f"metalpdb_binding_windows_len{window_len}_unique_peptide_metal.csv"
    summary_csv = output_dir / f"metalpdb_binding_windows_len{window_len}_summary_by_metal.csv"
    failures_csv = output_dir / f"metalpdb_binding_windows_len{window_len}_failures.csv"

    # Combine raw chunks by streaming append.
    first = True
    for chunk in iter_csv_files(window_part_files, chunksize=combine_chunksize):
        chunk.to_csv(all_csv, mode="w" if first else "a", header=first, index=False)
        first = False
    if first:
        pd.DataFrame().to_csv(all_csv, index=False)

    first = True
    for chunk in iter_csv_files(failure_part_files, chunksize=combine_chunksize):
        chunk.to_csv(failures_csv, mode="w" if first else "a", header=first, index=False)
        first = False
    if first:
        pd.DataFrame().to_csv(failures_csv, index=False)

    # Deduplicate streamed chunks.
    dedup_cols = ["metal", "pdb", "chain", "bind_resseq", peptide_col]
    seen_dedup = set()
    seen_peptide_metal = set()
    first_dedup = True
    first_pep_metal = True

    # Summary counters based on deduplicated windows.
    summary = defaultdict(lambda: {
        "n_windows": 0,
        "unique_peptides": set(),
        "pdbs": set(),
        "uniprots": set(),
    })

    for chunk in iter_csv_files(window_part_files, chunksize=combine_chunksize):
        if chunk.empty or peptide_col not in chunk.columns:
            continue

        dedup_keep_rows = []
        pep_metal_keep_rows = []

        for row in chunk.to_dict("records"):
            key = tuple(row.get(c) for c in dedup_cols)
            if key not in seen_dedup:
                seen_dedup.add(key)
                dedup_keep_rows.append(row)

                metal = row.get("metal")
                summary[metal]["n_windows"] += 1
                summary[metal]["unique_peptides"].add(row.get(peptide_col))
                summary[metal]["pdbs"].add(row.get("pdb"))
                uni = row.get("uniprot")
                if not is_missing(uni):
                    summary[metal]["uniprots"].add(str(uni))

            pm_key = (row.get("metal"), row.get(peptide_col))
            if pm_key not in seen_peptide_metal:
                seen_peptide_metal.add(pm_key)
                pep_metal_keep_rows.append(row)

        if dedup_keep_rows:
            pd.DataFrame(dedup_keep_rows).to_csv(
                dedup_csv,
                mode="w" if first_dedup else "a",
                header=first_dedup,
                index=False,
            )
            first_dedup = False

        if pep_metal_keep_rows:
            pd.DataFrame(pep_metal_keep_rows).to_csv(
                peptide_metal_csv,
                mode="w" if first_pep_metal else "a",
                header=first_pep_metal,
                index=False,
            )
            first_pep_metal = False

    if first_dedup:
        pd.DataFrame().to_csv(dedup_csv, index=False)
    if first_pep_metal:
        pd.DataFrame().to_csv(peptide_metal_csv, index=False)

    summary_rows = []
    for metal, vals in summary.items():
        summary_rows.append({
            "metal": metal,
            "n_windows": vals["n_windows"],
            "n_unique_peptides": len(vals["unique_peptides"]),
            "n_pdb_structures": len(vals["pdbs"]),
            "n_uniprot": len(vals["uniprots"]),
        })
    summary_df = pd.DataFrame(summary_rows)
    if len(summary_df):
        summary_df = summary_df.sort_values(["n_windows", "n_unique_peptides"], ascending=False)
    summary_df.to_csv(summary_csv, index=False)

# ---------------------------------------------------------------------
# Main extraction
# ---------------------------------------------------------------------
def extract_binding_windows(
    input_csv: Path,
    output_dir: Path,
    window_len: int = 10,
    pad_termini: bool = False,
    cif_cache_dir: Optional[Path] = None,
    max_rows: Optional[int] = None,
    save_every_k: int = 1000,
    make_final_files: bool = False,
    clear_structure_cache_on_flush: bool = True,
) -> List[Path]:
    input_csv = Path(input_csv)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if cif_cache_dir is None:
        cif_cache_dir = output_dir / "cif_cache"
    cif_cache_dir.mkdir(parents=True, exist_ok=True)

    if save_every_k <= 0:
        raise ValueError("save_every_k must be a positive integer.")

    parts_dir = output_dir / "parts"
    parts_dir.mkdir(parents=True, exist_ok=True)
    manifest_rows: List[Dict[str, Any]] = []
    window_part_files: List[Path] = []
    failure_part_files: List[Path] = []
    part_idx = 1
    total_windows_written = 0
    total_failures_written = 0

    df = pd.read_csv(input_csv)
    if max_rows is not None:
        df = df.head(max_rows).copy()

    pdb_col = first_existing_column(df, ["pdb_code", "pdb", "pdb_id", "PDB", "PDB_ID"])
    metal_col = first_existing_column(df, ["query_metal", "metal", "metal_symbol", "Metal"])
    site_col = first_existing_column(df, ["site", "site_id", "id"])
    uniprot_col = first_existing_column(df, ["uniprot", "UniProt", "uniprot_id"])
    molecule_col = first_existing_column(df, ["molecule", "protein", "macromolecule", "name"])
    organism_col = first_existing_column(df, ["organism", "species"])

    if pdb_col is None:
        raise ValueError("Could not find a PDB column. Expected one of: pdb_code, pdb, pdb_id.")

    rows: List[Dict[str, Any]] = []
    failures: List[Dict[str, Any]] = []
    structure_cache: Dict[str, Any] = {}
    chain_cache: Dict[Tuple[str, str], Tuple[str, List[int], List[str]]] = {}

    print(f"Input rows: {len(df)}")
    print(f"Using PDB column: {pdb_col}")
    print(f"Using metal column: {metal_col}")
    print(f"Saving a new part CSV every {save_every_k} input rows")

    peptide_col = f"peptide_len{window_len}"
    label_col = f"binding_site_labels_len{window_len}"
    window_columns = [
        "source_row_index", "site", "metal", "pdb", "chain", "bind_resseq",
        "bind_residue_aa", "center_idx_in_chain_sequence", "window_start_idx",
        "window_end_idx", "center_pos_in_window", "uniprot", "molecule",
        "organism", peptide_col, label_col, "chain_sequence_length",
    ]
    failure_columns = [
        "row_index", "pdb", "metal", "chain", "bind_resseq", "center_idx", "reason",
    ]

    def flush_part(processed_until_row: int, force: bool = False) -> None:
        nonlocal rows, failures, part_idx, total_windows_written, total_failures_written
        nonlocal structure_cache, chain_cache

        if not force and not rows and not failures:
            return
        if force and not rows and not failures:
            return

        window_path = parts_dir / f"metalpdb_binding_windows_len{window_len}_part_{part_idx:06d}.csv"
        failure_path = parts_dir / f"metalpdb_binding_windows_len{window_len}_failures_part_{part_idx:06d}.csv"

        n_windows = write_chunk_csv(rows, window_path, columns=window_columns)
        n_failures = write_chunk_csv(failures, failure_path, columns=failure_columns)

        window_part_files.append(window_path)
        failure_part_files.append(failure_path)
        total_windows_written += n_windows
        total_failures_written += n_failures
        manifest_rows.append({
            "part": part_idx,
            "processed_until_input_row": processed_until_row,
            "window_csv": str(window_path),
            "failure_csv": str(failure_path),
            "n_windows": n_windows,
            "n_failures": n_failures,
        })

        print(
            f"Saved part {part_idx:06d}: windows={n_windows}, failures={n_failures}, "
            f"processed_until_row={processed_until_row}"
        )

        rows.clear()
        failures.clear()
        part_idx += 1

        if clear_structure_cache_on_flush:
            structure_cache.clear()
            chain_cache.clear()

    for i, row in df.iterrows():
        pdb_id = clean_pdb_id(row.get(pdb_col))
        if pdb_id is None:
            failures.append({"row_index": i, "reason": "missing_or_invalid_pdb"})
            continue

        binding_map = extract_binding_residues_from_row(row, metal_col=metal_col)
        if not binding_map:
            failures.append({"row_index": i, "pdb": pdb_id, "reason": "no_amino_acid_ligand_residues_parsed"})
            continue

        try:
            if pdb_id not in structure_cache:
                cif_path = download_cif(pdb_id, cif_cache_dir=cif_cache_dir)
                structure_cache[pdb_id] = load_structure(cif_path)
            structure = structure_cache[pdb_id]
        except Exception as e:
            failures.append({"row_index": i, "pdb": pdb_id, "reason": f"cif_download_or_parse_failed: {e}"})
            continue

        for (metal, chain_id), bind_resnums in binding_map.items():
            try:
                key = (pdb_id, chain_id)
                if key not in chain_cache:
                    chain_cache[key] = chain_sequence_and_resseqs_from_structure(structure, chain_id)
                seq, resseqs, resnames = chain_cache[key]
            except Exception as e:
                failures.append({
                    "row_index": i,
                    "pdb": pdb_id,
                    "metal": metal,
                    "chain": chain_id,
                    "reason": f"chain_not_found_or_parse_failed: {e}",
                })
                continue

            if not seq:
                failures.append({"row_index": i, "pdb": pdb_id, "chain": chain_id, "reason": "empty_chain_sequence"})
                continue

            # Map PDB author residue number to all sequence indices that carry that residue number.
            # Usually one index, but list is safer if insertion-code handling collapses residue IDs.
            resseq_to_indices: Dict[int, List[int]] = defaultdict(list)
            for idx, resseq in enumerate(resseqs):
                resseq_to_indices[int(resseq)].append(idx)

            for bind_resseq in sorted(bind_resnums):
                center_indices = resseq_to_indices.get(int(bind_resseq), [])
                if not center_indices:
                    failures.append({
                        "row_index": i,
                        "pdb": pdb_id,
                        "metal": metal,
                        "chain": chain_id,
                        "bind_resseq": bind_resseq,
                        "reason": "binding_residue_not_in_standard_chain_sequence",
                    })
                    continue

                for center_idx in center_indices:
                    win = centered_window(seq, center_idx, window_len=window_len, pad_termini=pad_termini)
                    if win is None:
                        failures.append({
                            "row_index": i,
                            "pdb": pdb_id,
                            "metal": metal,
                            "chain": chain_id,
                            "bind_resseq": bind_resseq,
                            "center_idx": center_idx,
                            "reason": "near_terminus_window_skipped",
                        })
                        continue

                    peptide, start, end, center_pos = win
                    rows.append({
                        "source_row_index": i,
                        "site": row.get(site_col) if site_col else None,
                        "metal": metal,
                        "pdb": pdb_id,
                        "chain": chain_id,
                        "bind_resseq": int(bind_resseq),
                        "bind_residue_aa": seq[center_idx] if 0 <= center_idx < len(seq) else None,
                        "center_idx_in_chain_sequence": int(center_idx),
                        "window_start_idx": int(start),
                        "window_end_idx": int(end - 1),
                        "center_pos_in_window": int(center_pos),
                        "uniprot": row.get(uniprot_col) if uniprot_col else None,
                        "molecule": row.get(molecule_col) if molecule_col else None,
                        "organism": row.get(organism_col) if organism_col else None,
                        f"peptide_len{window_len}": peptide,
                        f"binding_site_labels_len{window_len}": label_string(window_len, center_pos),
                        "chain_sequence_length": len(seq),
                    })

        if (i + 1) % 100 == 0:
            print(
                f"Processed {i + 1}/{len(df)} rows; "
                f"current-part windows={len(rows)}; total-written windows={total_windows_written}"
            )

        if (i + 1) % save_every_k == 0:
            flush_part(processed_until_row=i + 1)

    flush_part(processed_until_row=len(df), force=True)

    pd.DataFrame(manifest_rows).to_csv(
        output_dir / f"metalpdb_binding_windows_len{window_len}_manifest.csv",
        index=False,
    )

    if make_final_files:
        build_final_outputs_from_parts(
            window_part_files=window_part_files,
            failure_part_files=failure_part_files,
            output_dir=output_dir,
            window_len=window_len,
        )

    print("\nSaved chunked outputs:")
    print(f"  parts folder: {parts_dir}")
    print(f"  manifest: {output_dir / f'metalpdb_binding_windows_len{window_len}_manifest.csv'}")
    print(f"  total window rows written: {total_windows_written}")
    print(f"  total failure rows written: {total_failures_written}")
    if make_final_files:
        print("  final combined/deduplicated files were also created")
    else:
        print("  final combined/deduplicated files were skipped; use --make-final-files if needed")

    return window_part_files

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract length-10 peptide windows centered on MetalPDB metal-binding residues."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=DEFAULT_INPUT_CSV,
        help="Input CSV, usually metalpdb_all_metals_unique/metalpdb_all_metals_all_records.csv",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output folder for peptide-window CSV files.",
    )
    parser.add_argument("--window-len", type=int, default=10, help="Peptide window length. Default: 10")
    parser.add_argument(
        "--pad-termini",
        action="store_true",
        help="Pad near-terminus windows with X instead of skipping them.",
    )
    parser.add_argument(
        "--cif-cache-dir",
        type=Path,
        default=None,
        help="Optional CIF cache folder. Default: <output-dir>/cif_cache",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=None,
        help="Optional quick-test limit on input rows.",
    )
    parser.add_argument(
        "--save-every-k",
        type=int,
        default=1000,
        help="Save current rows to a new part CSV every K input rows. Default: 1000.",
    )
    parser.add_argument(
        "--make-final-files",
        action="store_true",
        help=(
            "After chunked extraction, also build combined, deduplicated, unique peptide-metal, "
            "summary, and failure CSVs. This uses more memory than chunked-only mode."
        ),
    )
    parser.add_argument(
        "--keep-structure-cache",
        action="store_true",
        help="Do not clear parsed structure/chain caches after each part. Faster but uses more RAM.",
    )
    args = parser.parse_args()

    extract_binding_windows(
        input_csv=args.input_csv,
        output_dir=args.output_dir,
        window_len=args.window_len,
        pad_termini=args.pad_termini,
        cif_cache_dir=args.cif_cache_dir,
        max_rows=args.max_rows,
        save_every_k=args.save_every_k,
        make_final_files=args.make_final_files,
        clear_structure_cache_on_flush=not args.keep_structure_cache,
    )


if __name__ == "__main__":
    main()
